### ISSUE TITLE
CONFIGURATION_NOT_FOUND error while going through the Quickstart steps

### ISSUE THREAD

**Issue by annie-elequin** [Camberi/firecms#101]
Trying to get quickstart up and running, but seeing this error when I click "Sign in With Google" on my deployed site: https://ninestone-content.firebaseapp.com

I'm sure I probably just missed a step somewhere, but that probably means the Quickstart guide could use some more clarification. 

The only thing I've changed was I replaced the firebaseConfig in the Quickstart App.tsx with my own values. 

![image](https://user-images.githubusercontent.com/20155539/123896750-c0692400-d927-11eb-86f0-a3412984b081.png)

**Comment by fgatti675** [comment]
Hi @annie-elequin !
Did you enable Google authentication in your Firebase project?
We can definitely do a better job at explaining the prerequisites, and will do :)

**Comment by fgatti675** [comment]
I added some additional Firebase instructions in
https://firecms.co/docs/firebase_setup/
