### ISSUE TITLE
Allow async function in PermissionsBuilder to use custom claims

### ISSUE THREAD

**Issue by davemecha** [Camberi/firecms#102]
It would be very helpful to be able to pass an async function to `PermissionsBuilder`, since `user.getIdToken()` returns a promise. 

I want to use custom claims for managing permissions and with being able to access the token inside the `PermissionsBuilder` I can access the custom claims, as they are passed with the token.

**Comment by fgatti675** [comment]
Hi @davemecha 
I have been looking into this and it's a bit trickier than it seems.
PermissionsBuilder is called a lot, every time a cell is rendered. If we make it asynchronous we would need to show a lot of loading indicators!
Would it work for you to load the user claims once, when the users logs in, and then pass that into the config?

If so, you can build the whole navigation asyncronously. In the quickstart example, a NavigationBuilder is used (which can be async) https://firecms.co/docs/quickstart

Can you give it a try and tell me if it works out?

In the next version I am adding a couple of utility functions, that might make your life easier, like being able to pass custom objects to the permission builder :)

**Comment by davemecha** [comment]
@fgatti675 Thanks for the feedback

I'm not sure how to accomplish that without directly using the firebase API.

``` ts
  const navigation: NavigationBuilder = ({ user }: NavigationBuilderProps) => ({
    ...
  });
```

The `NavigationBuilder` gets the `user` but it may not return a promise as well. I could try getting the user somehow outside the builder (with the firebase API) and only initialize the `navigation` when the user is ready.

**Comment by fgatti675** [comment]
Hi @davemecha 
I think it was already possible before, but I have made it a bit easier to add this kind of behaviour in version 0.44.0
You can return a promise in the `NavigationBuilder`, so you could get your user permissions and then save them in the `authController`, which is an internal controller you can get in some callbacks, as well as via a hook, if you have a custom component.
I have modified the quickstart example to cover your use case:
https://firecms.co/docs/quickstart/
You fetch your data in the navigation builder, save it in the `extra` field of the `authController` and then retrieve it in your permissions builder :)

**Comment by davemecha** [comment]
Nice, works... :)

```ts
const isAdmin = !!(await user?.getIdTokenResult())?.claims?.admin;
authController.setExtra({ isAdmin });

[...]

buildCollection({
  [...]
      permissions: () => ({
        edit: !!authController.extra?.isAdmin,
        create: !!authController.extra?.isAdmin,
        delete: !!authController.extra?.isAdmin,
      }),
  [...]
})
[...]
```

But now I get how I could have achieved this before... :) I could have used the `useAuthController()` hook in my app somewhere and then add my extras to it. I now do this in a custom CMSView to handle the permissions there accordingly. :)

**Comment by fgatti675** [comment]
Awesome! Happy to know it works for you :)
I need to add some more examples for these kind of use cases
