### ISSUE TITLE
How to put CMS to a subroute of my app?

### ISSUE THREAD

**Issue by davemecha** [Camberi/firecms#103]
I try to find out how I could place FireCMS in a subroute.

I tried this code, but all subroutes in CMS are still relative to `/` istead of `/cms`:

``` tsx
<Route path="/cms">
  <CMSApp
    name={ 'My Online Shop' }
    authentication={ myAuthenticator }
    navigation={ navigation }
    firebaseConfig={ firebaseConfig }
  />
</Route>
```

**Comment by fgatti675** [comment]
Hi @davemecha 
Unfortunately this is not straight forward right now, but I am checking if should just work in the next version of React Router
https://reacttraining.com/blog/react-router-v6-pre/#introducing-routes
We will definitely migrate when possible.
I'm keeping this open as a enhancement request

**Comment by fgatti675** [comment]
This is now possible in version 1.0.0-beta1 :)
You have a `basePath` prop in `FirebaseCMSApp` (previously `CMSApp`)  or you can have more routes customisation if you follow the steps in https://firecms.co/docs/custom_cms_app
