### ISSUE TITLE
How to prevent creating document in subcollection based on id of the parent document?

### ISSUE THREAD

**Issue by olivoil** [Camberi/firecms#107]
Hi! Thanks for authoring FireCMS!

Is it possible to condition the create permission in a subcollection based on the id of the parent document?

For example, do something like this:

```
collections: [
        buildCollection({
          relativePath: "parent",
          schema: parentSchema,
          permissions: ({ user, entity, authController }) => ({
            edit: true,
            create: true,
            delete: true,
          }),
          subcollections: [
            buildCollection({
              relativePath: "children",
              schema: childSchema,
              permissions: ({ user, entity, authController }) => ({
                edit: true,

                // NEED HELP HERE
                // entity is null, how can I condition the creation of an item in a subcollection on the value of the parent id ?
                create: authController.extra.id === entity.reference.parent.id,


                delete: true,
              }),
```

**Comment by fgatti675** [comment]
Hi @olivoil !
I'm adding the collectionPath to the `permissionBuilder` props ;)

**Comment by fgatti675** [comment]
Hi @olivoil 
So 2 new parameters have been added to `PermissionBuilder` in version 0.45.1:
- `collectionPath` which tells you the full path above the current entity.
- `context` which is the general app context data.
With that info, you can either parse the `collectionPath` and find the id yourself, or you can use an utility function called [getNavigationFrom](https://firecms.co/docs/api/functions/getnavigationfrom) to which you can pass those 2 parameters as `path` and `context` and get an object that describes the full navigation path, based on your cofing.
Let me know if this helps!

**Comment by olivoil** [comment]
That was fast, I'll test it later today, thanks a ton!
