### ISSUE TITLE
edit permission not respected on parent when opening side panel directly from subcolletion button

### ISSUE THREAD

**Issue by olivoil** [Camberi/firecms#109]
It looks like there is a bug when opening the subcollection panel of a parent item.

When the `edit` permission is set to `false` on the parent, opening the side panel by clicking on the edit icon shows the side panel in view-only mode. However, opening the side panel by clicking on a sub-collection button shows the side panel in edit mode.

For example, with this configuration:

```
buildCollection({
  relativePath: "parents",
  schema: parentSchema,
  permissions: () => ({
    edit: false,
    create: true,
    delete: true,
  }),
  subcollections: [
    buildCollection({
      relativePath: "children",
      schema: childSchema,
      name: "Children",
      permissions: () => ({
        edit: true,
        create: true,
        delete: true,
      }),
    }),
  ],
});
```

clicking on the edit icon in the "id" column of a parent opens the parent side panel in view-only mode, but clicking on the "CHILDREN" button in the parent row opens the parent side panel in edit mode.

**Comment by fgatti675** [comment]
good catch! fixed in version 0.46.0
