### ISSUE TITLE
add `collectionPath` to `PropertyBuilderProps` ?

### ISSUE THREAD

**Issue by olivoil** [Camberi/firecms#113]
Hi!

Would it be possible to add `collectionPath` to `PropertyBuilderProps` ?

In top level collections, it's handy to have the `entityId`. In subcollections, it would be practical to get the parentId as well, for example, to use it in the storage path or metadata of a file:

```
buildSchema({
  name: "will be used in a subcollection",
  properties: {
    image: ({ collectionPath, context }) => ({
      dataType: "string",
      config: {
        storagePath: `parents/${parentId from collectionPath}/images`,
        metadata: {
         customMetadata: { collectionPath },
        }
      }
    }),
  },
})
```

**Comment by fgatti675** [comment]
Hi, added the `collectionPath` in version 0.47.0 ;)
In any case, it was already possible to have a callback, specifically for the `storagePath`  
```
buildSchema({
  name: "will be used in a subcollection",
  properties: {
    image: ({ collectionPath }) => ({
                dataType: "string",
                config: {
                    storageMeta: {
                        mediaType: "image",
                        storagePath: ({entityId}) => { // all the props in the link below
                            return "images";
                        },
                        acceptedFiles: ["image/*"],
                        fileName: (context) => {
                            return context.file.name;
                        }
                    }
                }
            }),
  },
})
```
The props for the callback in the `storagePath` can be found here: https://firecms.co/docs/api/types/uploadedfilecontext/

**Comment by olivoil** [comment]
Awesome, thank you for letting me know about the other callbacks!

**Comment by fgatti675** [comment]
I will work on improving the docs, thanks a lot on your sponsorship :)
