### ISSUE TITLE
Google Sign in Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by dhazeley** [Camberi/firecms#116]
After deploying FireCMS through firebase hosting and enabling Google Provider in Firebase Authentication, I get the following error upon login:

Authorization Error
Error 400: redirect_uri_mismatch
You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.

I don't see any additional options in the Firebase console or FIreCMS to configure an OAuth redirect url

**Comment by fgatti675** [comment]
Hi @dhazeley sorry for the late reply, I was on vacation.
Could you solve this?
I suspect this is related to the config of your `Authorized domains`.
If you are deploying the app to a different domain you need to add it there.

**Comment by dhazeley** [comment]
@fgatti675 No problem.

I could not get it solved and I do believe I have firebase set up correctly. Assuming my domain name is `example.com`:
- In Firebase Hosting console, I added `cms.example.com` as a custom domain. It is being hosted correctly on that domain.
- In Firebase Authentication Console, I added both `example.com` and `cms.example.com` as Authorized Domains.

**Comment by fgatti675** [comment]
I think this error is due to some specific config in your setup
Maybe you can check https://console.cloud.google.com/apis/credentials/consent?project=YOUR_PROJECT
and see if everything is in order?

**Comment by dhazeley** [comment]
After going through all the necessary steps in the **Edit App** page of the Oauth consent screen, and completing the Domain verification, I am still encountering the same problem.

**Comment by dhazeley** [comment]
There was an error with my firebase config. Sorry I didn't catch that earlier.
