### ISSUE TITLE
./node_modules/@camberi/firecms/dist/index.modern.js Attempted import error: 'firebase/app' does not contain a default export (imported as 'firebase').

### ISSUE THREAD

**Issue by nathanbenhamou** [Camberi/firecms#117]
Hello,
Following the quickstart tutorial, after Yarn start I have the following error

./node_modules/@camberi/firecms/dist/index.modern.js
Attempted import error: 'firebase/app' does not contain a default export (imported as 'firebase').

Any idea? thanks

**Comment by fgatti675** [comment]
Hi @nathanbenhamou 
Which version of firebase are you using?
Currently we are supporting versions 7 and 8.
Next version will support 9

**Comment by nathanbenhamou** [comment]
I'm on 8.13.1

**Comment by fgatti675** [comment]
Hi @nathanbenhamou 
I can reproduce this, I'll fix it and let you know :)

**Comment by fgatti675** [comment]
In the meantime, setting the Firebase version to 8.5.0  in `package.json` should work :)

**Comment by fgatti675** [comment]
Yes that problem is due to installing firebase now sets the version to 9.
The docs have been update to use 8. `yarn add firebase@8`
We have already a version in development for SDK 9 in case anyone is interested
