### ISSUE TITLE
Discard button did not navigate back to list

### ISSUE THREAD

**Issue by shaniceweiwei** [Camberi/firecms#12]
In document editing page, the Discard button next to Save button does not seems navigate back to the previous page.

**Comment by fgatti675** [comment]
Hi @shaniceweiwei, we will add back navigation :)
How about also adding the same behaviour for the save button?

**Comment by shaniceweiwei** [comment]
> Hi @shaniceweiwei, we will add back navigation :)
> How about also adding the same behaviour for the save button?

Yes. probably Save button too, that would be ease for user.

**Comment by fgatti675** [comment]
Hi @shaniceweiwei, navigation has been completely revamped in the latest version and this is fixed. You may want to check it out!
