### ISSUE TITLE
Array fields still show the 'Add' button if disabled

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#121]
Hi there!

Hope you have been well! It has been a while since I tried the latest versions and I must say firecms is coming out great! :)

I was doing some custom validation based on values. I have a boolean field which if set to true, enables an array field. However, the array field still shows the 'Add' button even if the boolean field is set to false. When clicking the 'Add' button with the boolean field as false, results in crashing the app. The two fields are as follows (in the schema)

`
hasVariants: {
            title: "Enable variants",
            longDescription: "You must set the variants if you enable this",
            dataType: "boolean",
        },
        variantList: ({values}) => ({
            title: "Variants",
            dataType: "array",
            validation: {
              required: values.hasVariants
            },
            disabled: !values.hasVariants && {
                clearOnDisabled: true,
                disabledMessage: "Enable variants to set this field"
            },
            of: {
                dataType: "map",
                properties: {
                    id: {
                        title: "Variant ID",
                        dataType: "number",
                        validation: {required: true}
                    },
                    name: {
                        title: "Name",
                        dataType: "string",
                        validation: {required: true}
                    },
                    durationSeconds: {
                        title: "Duration",
                        dataType: "number",
                        validation: {required: true},
                        config: {
                            enumValues: {
                                604800: "WEEK",
                                2678400: "MONTH",
                                [-1]: "FOREVER"
                            }
                        },
                    }
                }
            }
        }),
`

I'll be thankful if you look into this!

**Comment by fgatti675** [comment]
Thank you! Hope you are well too :)
Fixing this in the next release

**Comment by fgatti675** [comment]
Fixed in version 0.50.0
