### ISSUE TITLE
'You have unsaved changes..' browser popup shows up after saving with a PreSave callback

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#123]
Hi

I set a custom field in a document based on another field in the PreSave callback. It works fine, but after pressing save it shows the 'You have unsaved changes..' message in the browser. At this point, the doc has already been saved, so the message can be confusing. Additionally, it can be annoying since users have to click save and then the ok button in the browser popup.

**Comment by fgatti675** [comment]
Good catch! 
We have a lot of internal changes in the `next` branch. It includes updates to MUI 5, React-router 6 and Firebase SDK 9, plus a lot of internal changes also affecting this behaviour. 
We will be releasing this as version 1.0.0-alpha1
I'll keeo you updated!

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi 
I have not been able to reproduce this bug in the latest version 1.0.0-beta2
Coul you verify this is fixed with your setup?
Thanks!

**Comment by fgatti675** [comment]
Quick heads up, we found the bug and will be fixed for version 1.0.0-beta5.
We are also working on the performance of the side panel :)

**Comment by fgatti675** [comment]
This should be fixed in version 1.0.0-beta5 ;)
