### ISSUE TITLE
Custom field validation

### ISSUE THREAD

**Issue by grind-t** [Camberi/firecms#127]
Is it possible to use validation for a custom field component that uses buildPropertyField function?
Example:
```tsx
const CustomField = ({
  property,
  value,
  name,
  tableMode,
  error,
  showError,
  includeDescription,
  context,
  setValue,
}: FieldProps<object>) => {
  useEffect(() => {
    if (!value) setValue({});
  }, []);

  return (
    <FormControl fullWidth error={showError}>
      {!tableMode && (
        <FormHelperText filled required={property.validation?.required}>
          <LabelWithIcon scaledIcon={true} property={property} />
        </FormHelperText>
      )}

      <Paper elevation={0}>
        {buildPropertyField({
          name: `${name}.sample`,
          property: {
            title: "Sample",
            dataType: "string",
            validation: {
              required: true,
            },
          },
          context,
        })}
      </Paper>

      {includeDescription && <FieldDescription property={property} />}

      {showError && typeof error === "string" && (
        <FormHelperText>{error}</FormHelperText>
      )}
    </FormControl>
  );
};
```
sample property validation doesn't work for this component.

**Comment by fgatti675** [comment]
Mmmm interesting, `buildPropertyField` is the exact same method used internally to build all the fields in the CMS, so validation should work just the same, when using it like in this case.
I'm flagging it as a bug and looking into it.

**Comment by fgatti675** [comment]
Also, thank you for using FireCMS!
We are commited to building an awesome library, if you have any feedback on enhancements or things you would like to improve, please feel free to create a Github issue, drop a line on https://www.reddit.com/r/firecms/ or reach me directly at hello@camberi.com :)

**Comment by grind-t** [comment]
@fgatti675 Thanks for this awesome library! I will definitely leave feedback if i have it.

**Comment by fgatti675** [comment]
Sorry @grind-t, I was actually wrong.
Validation passed to properties in `buildPropertyField` has no effect. But you can achieve the same result by passing that validation to the parent property, when defining your entity schema:
```tsx
// ...
        validated_custom: {
            dataType: "map",
            title: "Validated custom field",
            properties: {
                sample: {
                    title: "Sample",
                    dataType: "string",
                    validation: {
                        required: true
                    }
                }
            },
            config: {
                Field: CustomField
            }
        },
// ..
```
