### ISSUE TITLE
How to disable singup ?

### ISSUE THREAD

**Issue by AnubhavMukhija** [Camberi/firecms#128]
I want to only enable signin in my application and if user doesn't exist in the firestore database it should show the corresponding error. 
Current Scenario - Currently I'm using email password signin method and with it if user email does not exist it opens a create account page(that is signup page). 
How can we prevent this?

**Comment by fgatti675** [comment]
You can do it since FirebaseUI, which we use for login supports it:
https://github.com/firebase/firebaseui-web#configure-email-provider

 ```
return <FirebaseCMSApp
        name={"My Online Shop"}
        signInOptions={[
            {
                provider: EmailAuthProvider.PROVIDER_ID,
                disableSignUp: { status: true }
            }
        ]}
        navigation={navigation}
    />;
```

**Comment by fgatti675** [comment]
Hi @niwasmala 
We replaced FirebaseUI with a custom solution since it was causing us trouble.
You currently can't disable sign in right now using `FirebaseCMSApp` but you should be able to achieve what you need using a custom app:
https://firecms.co/docs/custom_cms_app

**Comment by nikolasCASAR** [comment]
Hey @fgatti675 . I have tried your CustomCMSApp with the following config:
`const DEFAULT_SIGN_IN_OPTIONS = [
  {
    provider: EmailAuthProvider.PROVIDER_ID,
    disableSignUp: { status: true },
  },
];`

I'm still able to sign up, please, do i do something wrong way  ?

**Comment by fgatti675** [comment]
Hi @nikolasCASAR 
If you are using `CustomCMSApp` you are responsible for displaying the views that you consider.
If you want to disable the login function, just remove the if statement here:
https://github.com/Camberi/firecms/blob/b3bb496d6571f7e33bb36b1ad8d279181d23d05a/example/src/CustomCMSApp.tsx#L151

**Comment by nikolasCASAR** [comment]
@fgatti675 i don't want to disable login function. My goal is to be able to login (sign in), BUT JUST IN CASE, i know the right email/password credentials. If i didn't know them, i would not be able to signup (register). The signup (register) seems to be part of <FirebaseLoginView />, your UI automatically offers signup (register) after login fails. If login fails, we need to disallow user to signup (register) by his free will, if i have to say it that way. Thank you a lot for your time :)

**Comment by ellej16** [comment]
Heya @nikolasCASAR ! Might interest you to check out my PR for improvement / feedback?
https://github.com/Camberi/firecms/pull/248

It addreses the same concerns you have :D
