### ISSUE TITLE
UI breaks when we add firestore rules and it returns false.

### ISSUE THREAD

**Issue by AnubhavMukhija** [Camberi/firecms#131]
Scenario - I want role based authorisation.

```
 match /admins/{id}{  
      allow read: if  request.auth != null && "super" in request.auth.token.roles;
    }
```

I have added a roles array in custom claims and checking if that contains "super", if this condition returns true this is working fine as it should have but if this returns false then the whole ui of fireCMS breaks as shown in the image,  going back to previous page/home page does nothing it still shows broken ui. 
![Screenshot from 2021-09-27 12-00-22](https://user-images.githubusercontent.com/51721222/134855811-6b4b9c5b-6820-4548-92e1-4e4bdc776d48.png)
![Screenshot from 2021-09-27 12-00-14](https://user-images.githubusercontent.com/51721222/134855820-6165d0ce-0da2-4e1b-84c3-02a475bcd02b.png)

**Comment by fgatti675** [comment]
I'm checking this

**Comment by AnubhavMukhija** [comment]
Hi @fgatti675, are there any updates on this?

**Comment by fgatti675** [comment]
Hi @AnubhavMukhija,
 I just trying disable the permissions in a collection and I get an error message in the CMS, version 1.0.0-beta1

<img width="970" alt="Screenshot 2021-10-04 at 18 12 36" src="https://user-images.githubusercontent.com/5120271/135888028-bb213cb9-931a-40e3-9567-29ca64ff5f09.png">
