### ISSUE TITLE
Integers with value of 0 not rendered in the collection view

### ISSUE THREAD

**Issue by marianmoldovan** [Camberi/firecms#14]
I have a collection with a number dataType, but it's not displayed properly in the collection view. It appears empty.

You can see the issue in this screenshot.
![image](https://user-images.githubusercontent.com/1479084/96571262-9e64cf80-12cb-11eb-898f-766b87b63441.png)

The issue does not affect the edit view.

**Comment by fgatti675** [comment]
Thanks for the catch!
