### ISSUE TITLE
entityId under PropertyOrBuilder should not be set when copying a doc

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#145]
Hi! I found another minor issue; I don't think it is necessarily an issue but more about consistency.

I have some fields that are dependent on whether the entityId has been set (that is the doc exists in firebase). This works fine for editing or creating new docs. When docs are being created, entityId is undefined which makes sense, and when docs are being edited entityId is set to the firebase doc id.

However, when we use the copy feature to create a new doc, the entityId in the copy dialog will be set to the entityId we initiated the copy from. Since some of the fields I have are dependent on whether the entityId is set they don't behave correctly when using the copy feature.

I can also imagine the entityId being useful in the copy scenario but in general, what I am looking for is to check for a property whether entity already exists or not (in the data store). Using entityId is the only way I think; so either entityId should be undefined or there should be another variable in the property builder that can allow us to check if the entity is already set in the data store. I might be making some mistakes here so let me know if there are indeed other ways to check that.

**Comment by fgatti675** [comment]
Fixed in version 1.0.0-beta3!
