### ISSUE TITLE
Error in Demo When Clicking Products

### ISSUE THREAD

**Issue by benwinding** [Camberi/firecms#149]
Tried using the demo application and did the following:

## Reproduce Via

- Clicked `Skip Login`
- Clicked `Products`
- Blank page, errors in console

## Error Screenshot

![image](https://user-images.githubusercontent.com/11782590/139633656-260c2e17-95ad-40a2-9b4f-394990e83a8a.png)

**Comment by fgatti675** [comment]
Thanks @benwinding fixed now!
