### ISSUE TITLE
Deleting a document does not delete the subcollections 

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#150]
Hi Francesco
We already discussed it shortly, I think it maybe makes sense to place it here, other users might have the same problem and are interested in a solution.

**The Problem**
When we delete in FireCMS a document, then only the fields on of the document are deleted, but not the subcollections. This results in "dead" records in firestore, which should be cleaned. I cannot imagine a business case, where subcollections should remain in the database, when the document itself is deleted. A user expects, that a document with all fields and structure is deleted, when he deletes it.

Could FireCMS not delete also the subcollections? Must each record be deleted?
If not, maybe a cloud function can help, however as I understand also the cloud function must delete single records?

**Comment by fgatti675** [comment]
Hi Andre,

It is not a good idea that FireCMS deletes subcollections. 
Here we come to one of the limitations of the collection/document model of NoSQL and Firestore in particular.

FireCMS is purely a frontend app and that is a task is better suited for the backend for these reasons:
- FireCMS could only delete the subcollections that are mapped in its configuration, but could not find other subcollections that have been created in other ways.
- A subcollection could have a large number of records, which need to get deleted one by one, which would take a significant amount of time. It is possible that the user would close the browser while this happens and leave the process uncompleted. It is also bad UX.

The best way to tackle this is to create a Cloud Function that listens to deletions in the collection and then proceeds to perform the deletion of the subcollections.

**Comment by Andre3424** [comment]
Thanks! I wonder: Since this is a common problem, are there not some ready-made cloud functions available?
