### ISSUE TITLE
Error when filtering and sorting in same list

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#151]
Hi!
When I apply a filter to a list and then sort, then I get an error "Error fetching data from the data source".
For working with data this is an important function to narrow data sets working on.
Can this be fixed? Is there a workaround?
thanks!

**Comment by fgatti675** [comment]
Hi Andre, 
Yes this can be fixed. If you check the console logs you will find a link to your Firebase project that allows to create an index in your database.
If you want to enable sorting and filtering by multiple properties you can specify the created index in your `EntityCollection` configuration using the field `filterCombinations`
Let me know if you need further help!

**Comment by Andre3424** [comment]
Thanks! We will try this way and I will send feedback later

**Comment by Andre3424** [comment]
Hi Francesco
We finally wanted to implement this. Currently we do not get any error, just the following happens
1: I apply a filter on column (MeditationID)
2: Then I sort by another column (UpdateDate)
Result: The filter is lost.

We have set the filter as follows:
![grafik](https://user-images.githubusercontent.com/65586807/163184273-a75e0dd2-9d24-4134-952e-3e9b98cab00d.png)

and the index
![grafik](https://user-images.githubusercontent.com/65586807/163184345-38057bb0-79b2-4b59-b99a-55d0b4d24ec0.png)

Do you have an idea why it does not work?
