### ISSUE TITLE
User in navigation builder is no firebase user

### ISSUE THREAD

**Issue by davemecha** [Camberi/firecms#152]
Checking permissions via custom claims in `NavigationBuilder` should work via the `user` object. 

Unfortunately accessing the token is not possible with the passed `user` and `authController`.

I tried various ways to get the user proper firebase user object (and commented out the lines one by one.

``` ts
  const nav: NavigationBuilder = async ({ user, authController }: NavigationBuilderProps) => {
    if (!user) return {};

    try {
      let token = await (user as User).getIdTokenResult(); // passed user is `any` so I have to cast it. Typing should be improved here.
      token = await getIdTokenResult(user, true);
      token = await getIdTokenResult(authController.user, true);
      token = await getIdTokenResult(authController.authDelegate.user, true);

      const isAdmin = !!token?.claims?.admin;
      if (!isAdmin) return {};
    }
    catch (err) {
      console.log(err);
      return {};
    }

    // generate proper navigation

    return {   ....   };
  };
```

The `user` is somehow a cloned object with some fields missing from the original firebase user. I think there is no point in providing the user, if it is not the firebase user instance and permissions are not available.

I also tried to pass it via the `authController` from the `authenticator` to the `NavigationBuilder` with `authController.setExtra({ isAdmin });` but this did not work either.

As a workaround I can use the firebase API to get my token data.

``` ts
async function isAdminUser() {
  const app = getApp();
  const auth = getAuth(app);

  if (!auth?.currentUser) return false;
  const token = await getIdTokenResult(auth.currentUser, true);
  return !!token?.claims?.admin;
}
```

I just call this function in my `NavigationBuilder`.

I don't think this is intended. In the alpha version (v 50) of FireCMS the correct user instance was provided. I had the problem after updating to the current 1.0 beta 3.

**Comment by fgatti675** [comment]
Hi @davemecha ,
As of the latest version, 1.0.0-beta4, you can now specify the user type as a generic (as long as it complies with our User interface, which Firebase users do), so you can do something like this:
```tsx
import { User as FirebaseUser } from "firebase/auth";
const nav: NavigationBuilder<FirebaseUser> = async ({ user, authController }: NavigationBuilderProps) => {
    if (!user) return {};

    // generate proper navigation

    return {   ....   };
  };
```
Let me know if this works for you and feel free to close the ticket ;)

**Comment by davemecha** [comment]
@fgatti675 Thanks, great. Now `getIdTokenResult()` is accessible again. :)

And the generic type is awesome. With this I can avoid the typecast.

**Comment by fgatti675** [comment]
Awesome, thanks for your feedback dave ;)
