### ISSUE TITLE
Datepicker does not open in the right position in table view

### ISSUE THREAD

**Issue by fgatti675** [Camberi/firecms#155]
The date picker opens in the top left corner instead of inline in the table view.
It opens in the right position when opening from the side form view
<img width="1039" alt="Screenshot 2021-11-15 at 16 03 18" src="https://user-images.githubusercontent.com/5120271/141804423-54facf3e-e00b-44db-9529-66a8308cbb8b.png">

**Comment by mkim219** [comment]
Hi @fgatti675! Can I work on this issue?

**Comment by fgatti675** [comment]
fixed in 1.0.0-rc.4
