### ISSUE TITLE
"Can't perform a React state update on an unmounted component." on multiple file upload

### ISSUE THREAD

**Issue by davemecha** [Camberi/firecms#157]
I created a property for my build schema.

``` ts
    gallery: {
      title: 'Gallery',
      dataType: 'array',
      of: {
        dataType: 'string',
        config: {
          storageMeta: {
            mediaType: 'image',
            storagePath: 'images',
            acceptedFiles: ['image/*'],
            metadata: {
              cacheControl: 'max-age=1000000',
            },
          },
        },
      },
    },
```

When I drag & drop files to the drop zone, I get a React error that state update is not possible on an unmounted component. 
 
![image](https://user-images.githubusercontent.com/137976/141821437-01bec7aa-7897-4afe-bee3-52732239cdc0.png)

There is a check missing, if the component is still mounted before setting the state in `StorageUploadProgress`.
https://github.com/Camberi/firecms/blob/981134b1021061298def6c665eac5531a1ad8b20/src/form/fields/StorageUploadField.tsx#L666

I had a good experience with stuff like this: https://www.npmjs.com/package/use-async-effect - that makes it easy to check for the component still being mounted. So maybe it's an option to set a file state to trigger the upload via an async effect.

**Comment by fgatti675** [comment]
There was a check for this case in version 1.0.0-beta5 ;)
