### ISSUE TITLE
List of entites does not refresh - component state issue

### ISSUE THREAD

**Issue by fabarea** [Camberi/firecms#161]
Maybe related to https://github.com/Camberi/firecms/issues/157

I get the following error after saving an entity. I tried with various collections / schema. The list is not refreshed in real time. I need to force refresh the page to see the change.

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/620730/142454098-170ed55b-141a-42ca-9e59-4d64ac76b70a.png">

```
  "dependencies": {
    "@businessman/config": "file:../../packages/businessman-config",
    "@businessman/types": "file:../../packages/businessman-types",
    "@camberi/firecms": "1.0.0-beta4",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "@mui/icons-material": "next",
    "@mui/lab": "^5.0.0-alpha.48",
    "@mui/material": "^5",
    "@mui/styles": "^5",
    "@mui/x-data-grid": "^5",
    "algoliasearch": "^4",
    "clsx": "^1.1.1",
    "firebase": "^9",
    "react": "^17",
    "react-dom": "^17",
    "react-firebase-hooks": "^3",
    "react-i18next": "^11",
    "react-router-dom": "^6",
    "react-scripts": "^4",
    "typescript": "^4"
  },
```

Error in detail:

index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Formik (http://localhost:3001/static/js/vendors~main.chunk.js:534148:19)
    at EntityForm (http://localhost:3001/static/js/vendors~main.chunk.js:59928:5)
    at div
    at http://localhost:3001/static/js/vendors~main.chunk.js:66288:73
    at Box (http://localhost:3001/static/js/vendors~main.chunk.js:441904:76)
    at div

**Comment by fgatti675** [comment]
Hi @fabarea 
This is a bug that should be happening only in the latest version (1.0.0-beta4)
You can rollback to a previous version or wait until the next release :)

**Comment by fabarea** [comment]
@fgatti675 oh thanks you! Indeed, it now works with beta 3.
