### ISSUE TITLE
List not refreshing

### ISSUE THREAD

**Issue by jfbourne** [Camberi/firecms#163]
Similar to issue: #161. I rolled back to beta-3 and use the latest beta-5 and still same issue.

**Comment by fgatti675** [comment]
Hi @jfbourne sorry about that, there was an additional bug we have found after the release of beta5, will be fixed for beta6

**Comment by jfbourne** [comment]
@fgatti675 Thank you for reaching out and your great work! I will wait for beta6

**Comment by PoloBustillo** [comment]
Same here :(

**Comment by fgatti675** [comment]
Should be fixed in 1.0.0-beta6 😉
