### ISSUE TITLE
URL keeps points to doc id if changes were made but not saved

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#171]
Hi there!

I am using 1.0.0-beta5 and noted this issue that if I edit a doc and close the side panel without saving, the URL address in the browser keeps pointing to the doc instead of pointing to the root collection. Minor issue but can be annoying when refreshing the page; additionally, if we try to close the browser we get the 'unsaved changes' popup even though the admin panel doesn't have any doc open (but the URL still points to the doc).

It may have been resolved in beta6 but I haven't tried that yet. Thanks as always for the awesome updates! :)

**Comment by fgatti675** [comment]
Thanks for the catch! 
I wasn't able to reproduce this in demo.firecms.co with version 1.0.0-beta6
Let me know if you can reproduce it
