### ISSUE TITLE
Ability to confirm changes before saving to firestore

### ISSUE THREAD

**Issue by fashionado** [Camberi/firecms#172]
Is there a callback or method to receive a callback before the changes on a document are saved to the database ? Ideally, I should be able to change multiple fields of a document and click save before the fields actually gets saved. 

or 

a callback before the saving which when returns false prevents the changes from being saved.

Thanks.

**Comment by fgatti675** [comment]
Yes, you can modify the values before getting saved:
https://firecms.co/docs/collections/saving_callbacks
and prevent it from happening if you throw an Error
