### ISSUE TITLE
Painfully slow

### ISSUE THREAD

**Issue by fashionado** [Camberi/firecms#174]
Hello,

Functionality wise FireCMS has pretty much everything that I needed for my project but it is painfully slow and sluggish. I tried on firefox and chrome on my local machine and it is very slow. I also tried the demo site and that too is not very responsive. 

Are there any settings that can be changed to make it responsive. 
Thanks.

**Comment by fgatti675** [comment]
Hi @fashionado,
There have been a bunch of performance improvements in version 1.0.0-beta8 that you can try checking out.
Anyhow, FireCMS has a lot of components and depending on the computer you are on, it may get slow if you have a collection with a lot of properties.
Some properties render fields that are more complex than others, suck as markdown or image upload fields.
There are some things you can do to improve the performance of your setup.
You can limit the properties that are displayed in collections views using the `properties` field in the collection level and pass the string of keys you want to display.
You can also disable inline editing in collections altogether for a performance boost, but then you can also edit data through the side dialog

**Comment by fashionado** [comment]
Hello @fgatti675 : Thank you for your response.

1. My collection is text only. There are no images.
2. Inline editing is also disabled. Double/Single Clicking (not sure which one) opens up the side-panel to edit but it takes very long time.

3. Also I noticed that Collection.properties by itself does not prevent the display of certain columns. I had to remove them from my types too. I need to display fewer columns in the collection view but when in the edit panel I want to display more fields.  But looks like it is not allowed. Is that correct ?

**Comment by fgatti675** [comment]
Hi @fashionado 
I have been looking into this.
So the `properties` prop in collections should limit the columns rendered in a collection like:
```
    const usersCollection = buildCollection({
        path: "users",
        schema: usersSchema,
        name: "Users",
        additionalColumns: [
            {
                id: "sample_additional",
                title: "Sample additional",
                builder: () => "Content of a generated column"
            }
        ],
        properties: ["first_name", "last_name", "sample_additional"]
    });
```
Also, I have done a pretty significant change in the memoization check of table cells and have reduced significantly the number of renders, which makes the current demo butter smooth in my computer.
Can you check https://demo.firecms.co/
and tell me if the performance feels better?
Thanks

**Comment by fashionado** [comment]
Hello @fgatti675,

Thank you for looking into this. I checked out the new demo. Since it is the same link so I don't have a true reference to compare against. But the new demo definitely feels much faster. But I think there is still lot of scope for improvement. e.g, My app that I'm trying to replace with FireCMS is still much more faster. 

Regarding the properties, thanks. It works now. I mistook it as schema.properties.
However, I realized that additionalColumns don't update if the underlying fields are changed. e.g, in the following code if firstName/lastName are changed by editing in the side panel, the column does not get refreshed after I click on "save".

additionalColumns: [
           {
               id: "full_name",
               title: "Full Name",
               builder: ({entity}) => {
                   let values = entity.values;
                   return `${values.firstName} ${values.lastName}`;
               }
           },

**Comment by fgatti675** [comment]
I'll look into this ;)

**Comment by fgatti675** [comment]
Version 1.0.0-beta9 has been released with significant performance improvements.
Also, in the additional column, you can now set a field called dependencies that is an array of properties that your column depends on like `["firstName", "lastName"]`

**Comment by fashionado** [comment]
@fgatti675 : the beta9 is quite responsive. Thank you.
