### ISSUE TITLE
Module not found: Can't resolve '@camberi/firecms'

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [Camberi/firecms#175]
I have followed the Quickstart guide and whenever I try to run the app, it fails with the following error:

```
Module not found: Can't resolve '@camberi/firecms' in '****\firecms-test\src'
```

Here's the [repo](https://github.com/YoussefRaafatNasry/firecms-test), and these are some things that I've tried but they all gave the same error:

 1. Delete both `node_modules` and `yarn.lock` and then run `yarn install` again.
 1. Use a different machine running linux instead of windows.
 1. Use [stackblitz](https://stackblitz.com/).
 1. Use `tsconfig.json` from the example.

**Comment by fgatti675** [comment]
Sorry about that, fixed in version 1.0.0-beta7
