### ISSUE TITLE
Remove the size filter on top left

### ISSUE THREAD

**Issue by fashionado** [Camberi/firecms#187]
Hello,

How can the top left filter be removed. It automatically appears for all collections and sometimes even gets applied as a filter preventing all the documents to appear. Thanks.

![Screen Shot 2021-12-22 at 9 40 52 PM](https://user-images.githubusercontent.com/95842625/147193751-82a3b2d2-b529-4d53-987f-124753aa5f07.png)

**Comment by Prottoy2938** [comment]
How can I remove it? Any solutions yet?

**Comment by WitchHuntCompose** [comment]
@fgatti675 Would like a follow-up on this if possible.

**Comment by GitMyCode** [comment]
looking for this too
