### ISSUE TITLE
How to filter on condition for collection to display with different roles

### ISSUE THREAD

**Issue by MarkXuan** [Camberi/firecms#188]
The my application has 2 roles: role A and role B. For each different user, the data will be displayed differently. Example: with production collection, Role A will display all records, Role B only display records has condition (status = "complete"). 
If I use initialFilter it only display for first loading app and I choose another filter it will get all data of production collection. 
Thank you.

**Comment by fgatti675** [comment]
Unfortunately this is not possible at the moment.
You could try splitting the collection in two, or maybe trying to filter out using Firestore security rules?
I am not sure that would work though
