### ISSUE TITLE
How to pass entity id or context to custom preview ? 

### ISSUE THREAD

**Issue by aimen08** [Camberi/firecms#194]
Hello i'm trying to preview the entityId inside custom preview , i know you can do that inside custom field with the help of the context parameter.

**Comment by fgatti675** [comment]
Hi @aimen08 
I think this is not possible at this time, do you still need it?

**Comment by aimen08** [comment]
no @fgatti675 , i found work around , managed to achieve same thing with the  `additionalColumns` option .which make sense more than using preview.
