### ISSUE TITLE
How to upload PDF file to storage?

### ISSUE THREAD

**Issue by rgtstha** [Camberi/firecms#196]
First of all, I want to thank all the contributors for making such an amazing backend for firebase. 

I am working on a project where I have to upload `pdf` documents. I don't see any options to upload such files. Since it only supports `media` upload, any way to upload a pdf file?

**Comment by fgatti675** [comment]
Hi @rgtstha 
so the `media` prop is only used for previewing the uploaded file.
You can filter the uploaded files to be only pdfs like this:
```
buildProperty({
            title: "Pdf",
            dataType: "string",
            config: {
                storageMeta: {
                    storagePath: "test",
                    acceptedFiles: ['application/pdf'],
                }
            }
        })
```

**Comment by rgtstha** [comment]
oh! that's awesome. Thank you.
