### ISSUE TITLE
Custom pages

### ISSUE THREAD

**Issue by faizaand** [Camberi/firecms#20]
Is it possible to have navigation links that render a React component instead of showing the data table? For example, I'd like to have a home page with usage statistics. Is that a feature in FireCMS currently?

**Comment by fgatti675** [comment]
Hi faizaand,

Yes! You can't change the home page but you can add extra pages to the root navigation

`const additionalViews = [
    {
        path: "your_path",
        name: "Name displayed in the menu",
        view: <YourComponent/>
    }
];

ReactDOM.render(
    <CMSApp
        name={"Your app"}
        authentication={authenticator}
        navigation={yourNavigationConfig}
        firebaseConfig={firebaseConfig}
        additionalViews={additionalViews}
    />,
    document.getElementById("root")
);`

This feature is not properly documented. 

We also plan to create a generic home page with links to the root collection, and we can also make it customisable, but for now I hope this helps

**Comment by faizaand** [comment]
That's helpful, thank you!

**Comment by haresh14** [comment]
Hi @fgatti675 customisation for home has been added to the app or still its not possible? Basically I want to add some analytics and form directly on home page.

**Comment by fgatti675** [comment]
Hi @haresh14 I just created a new issue for it

**Comment by fgatti675** [comment]
This is now possible in version 1.0.0-beta1 :)
