### ISSUE TITLE
Reference path of "false" throws error

### ISSUE THREAD

**Issue by plvnts** [Camberi/firecms#215]
Referring to: 
https://firecms.co/docs/entities/properties/reference#path
https://firecms.co/docs/api/interfaces/ReferenceProperty/#path

Apparently, the path of a reference can be set to "false" if the schema is unknown. However, I get the error
```Type 'boolean' is not assignable to type 'string'.```
when setting the reference path to false.

**Comment by fgatti675** [comment]
Man, I silently pushed that change yesterday and wasn't expecting anyone to find it before release!
That change is not live yet despite being in the docs.
If you would like to use it anyway you can use the nightly build:

    "@camberi/firecms": "pre",

**Comment by plvnts** [comment]
Haha perfect! You're doing an amazing job!
