### ISSUE TITLE
Additional buttons in collection?

### ISSUE THREAD

**Issue by faizaand** [Camberi/firecms#22]
Does FireCMS allow you to add custom buttons on the toolbar of the collection view? I'd like to be able to add an "Export" button here, but I can't find the place to add components to the toolbar.

![Screen Shot 2020-11-27 at 4 36 48 PM](https://user-images.githubusercontent.com/6227145/100485619-bf8cbd00-30ce-11eb-8121-594d6b140062.png)

**Comment by fgatti675** [comment]
Hi @faizaand, this is pretty easy to implement and will add the feature soon :)

**Comment by fgatti675** [comment]
Published in version 0.23.0
