### ISSUE TITLE
Portal issue with fresh quickstart install

### ISSUE THREAD

**Issue by elololex** [Camberi/firecms#220]
Hi All,

Creating a clean project using the quickstart guide returns the below issue. I've tried it a few times now and still getting the same result. 

ERROR in ./node_modules/@camberi/firecms/dist/index.es.js 9191:13-19
export 'Portal' (imported as 'Portal') was not found in '@mui/material

Any ideas?

Thanks

**Comment by fgatti675** [comment]
Hi @elololex ,
seems like it is a problem with `mui` 5.4.0
I have tried setting the dependencies explicitly to 
```
    "@mui/material": "5.3.0",
    "@mui/styles": "5.3.0",
```
and it works fine.
I will check on how to fix it for the future release

**Comment by elololex** [comment]
Thanks @fgatti675  for the quick response. Downgrading to 5.3.0 worked - Thanks for your help 👍

**Comment by fgatti675** [comment]
No worries, they added a breaking change in mui 5.4
We are fixing the wrong import in the next release
