### ISSUE TITLE
Error with @mui/material 5.4.0

### ISSUE THREAD

**Issue by Evaldash** [Camberi/firecms#222]
An error is present when using the quick guide:

ERROR in ./node_modules/@camberi/firecms/dist/index.es.js 9191:13-19
export 'Portal' (imported as 'Portal') was not found in '@mui/material' (possible exports:...

I was able to make it work by downgrading to @mui/material ver 5.3.1, seems to be an incompatiblity with the new version.

**Comment by fgatti675** [comment]
Hi @Evaldash 
We are aware of this bug, they introduced a breaking change in version 5.4.0
It is already fixed in code and will be shipped with the next release

**Comment by fgatti675** [comment]
Fixed in version 1.0.0-rc.2
