### ISSUE TITLE
Pre-display Callback just like Pre-save callback

### ISSUE THREAD

**Issue by fashionado** [Camberi/firecms#224]
I have an editable field which is saved as string in Firestore. It is an ID of a document in a foreign collection. 

```
type Author{
   id: String
}
type Book{
  id: String
  author: String
}


```
In FireCMS, schema I define this field as "reference" type so that when displaying this field FireCMS can use the appropriate document display name from the foreign collection instead of the string. 

On pre-save, I map the reference type to just the string ID before saving it to the database.
```
Book.author = remove 'author/' from 'author/<id>' and just save the id.
```

But next time, when I try to display that field, I get "reference error" which is expected as the field was saved as "string" and not "reference".

Is there a way for me change the string field value back to a  reference type before FireCMS processes it to display ?

```
Book.author = 'author/' + Book.author
```

Or if there is a better way of specifying authors when a Book.author is edited and displayed ? I need to be able to show all the possible authors (just like a "reference" type does).

Thank you.

**Comment by fgatti675** [comment]
Hi @fashionado 
There is a new `onFetch` hook that you can use exactly for this use case :)
