### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by Vixxd** [Camberi/firecms#226]
Hi there, I'm wondering to what extent the CMS is customizable? I'd like to replace the logo image and CSS with my own but I am not sure where to start. Thanks!

EDIT:

I have been trying to reverse engineer this for some time and I'm currently trying to use the `createCMSDefaultTheme` method in `CustomCMSApp.tsx` from the Example in this repo. Unfortunately, this does not change the colour from the default material blue - any help would be appreciated.

```
const primaryColor = "#000000";
const secondaryColor = "#000000";
const fontFamily = "Montserrat";
const theme = createCMSDefaultTheme({ mode, primaryColor, secondaryColor, fontFamily });
```

EDIT2: Searching GitHub for other people who have used FireCMS, I was able to get it working by setting the values in the FirebaseCMSApp (https://github.com/jjl-tech/takeizi-cms/blob/c89b1e651e7fcee3ee60b7ea335992db4052d511/example/src/MyApp/index.tsx):

```
    return <FirebaseCMSApp
         ...
        primaryColor="#033155"
        secondaryColor="#4dabf7"
    />;
```

**Comment by fgatti675** [comment]
Hi @Vixxd glad you could make it work
Both ways you described should work
