### ISSUE TITLE
onDelete hook no longer gives values

### ISSUE THREAD

**Issue by faizaand** [Camberi/firecms#23]
The delete hook was moved into the entity schema in 814fbb3bf560e1b5ae80e53eb335e7c7d2cd8d42, but now it no longer provides the values of the deleted record. Is there a chance this field can be re-added? It's useful because since it's deleted, we can't access those values anymore, but we might need some of the documents' data to finish the deletion.

**Comment by fgatti675** [comment]
Added the deleted entity in 0.18.1 :)

**Comment by faizaand** [comment]
Works great, thanks!
