### ISSUE TITLE
How to allow duplicate enum selections

### ISSUE THREAD

**Issue by Vixxd** [Camberi/firecms#230]
I have an entity type (a 'bucket') of which I want to be able to hold one or more of the following properties:
- high
- medium
- low

e.g.
Bucket 1: High, High, Low
Bucket 2: Medium, Low, Low

### Scenario 1
I can do this in a string array as follows:
![image](https://user-images.githubusercontent.com/5870958/154181291-6a66d812-5592-4094-8118-79d4525f120c.png)

```
export const bucketsSchema = buildSchema({
    name: "Bucket",
    properties: {
        items: {
            title: "Item Values",
            dataType: "array",
            of: {
                    dataType: "string",
            }
        },
```

However, I would like high/medium/low to be pre-defined rather than typed in by the user. 

### Scenario 2 
If I configure as an enum or reference, I can only select one of each item (e.g. 'high' is either ticked or unticked, I cannot select 'high' twice):
![image](https://user-images.githubusercontent.com/5870958/154181604-892a22ba-e81f-420d-9818-d5a0c89f734f.png)

```

export const bucketsSchema = buildSchema({
    name: "Bucket",
    properties: {
        items: {
            title: "Item Values",
            dataType: "array",
            of: {
                dataType: "string",
                config: {
                    enumValues: {
                        high: "High",
                        medium: "Medium",
                        low: "Low"
                    }
                }
```

### Question
How can I alter the enum configuration so that I can allow the same value to be added twice in scenario (2)?
Or, failing that, how can I alter the "string" array choices in scenario (1) so that I can select from a dropdown list of these three values?

Thanks.

### Edit1: Attempt using custom-shaped array previews
I tried creating a custom-shaped array for the product value & quantity of that value (and it seems a bit extreme haha) but unfortunately got the following error regarding nested arrays:
```Bucket: Error saving Function setDoc() called with invalid data. Nested arrays are not supported (found in document buckets/hQtlG7IdbAoYfR1PzuOU)```

Array:
```
export const bucketsSchema = buildSchema({
    name: "Bucket",
    properties: {
        items: {
            title: "Content",
            description: "Example of a complex array with multiple properties as children",
            dataType: "array",
            columnWidth: 450,
            of: {
                title: "Quantity of Product Value Types",
                dataType: "array",
                config: {
                    Field: CustomShapedArrayField,
                    Preview: CustomShapedArrayPreview,
                    customProps: {
                        properties: [
                            buildProperty({
                                dataType: "string",
                                title: "Product Cost",
                                config: {
                                    enumValues: prod_cost
                                },
                                columnWidth: 175,
                            }),
                            buildProperty({
                                dataType: "number",
                                title: "Quantity"
                            })
                        ]
                    }
                }
            }
        },
```

Visualisation:
![image](https://user-images.githubusercontent.com/5870958/154185553-74d3af2c-3b98-4ea4-ae3d-8fedffe23a97.png)

## Edit2: Simple approach
Sometimes overcomplicating things isn't necessary...
![image](https://user-images.githubusercontent.com/5870958/154186176-ac26ebd1-9407-4f68-8082-edc3fc0c7ec9.png)

**Comment by fgatti675** [comment]
Hi @Vixxd 
I think the only way to achieve this right now is by implementing your own custom field:
https://firecms.co/docs/entities/custom_fields
The custom shaped array is an example of how you can build your field, you probably want to create your own custom one.
I guess you would include 3 selects that hold all 3 different values, so you can pick the values as you need.
The example in the docs is simpler and probably a better starting point.
