### ISSUE TITLE
Unclear how to use useCollectionFetch

### ISSUE THREAD

**Issue by josephclawrence** [Camberi/firecms#235]
I am attempting to use useCollectionFetch to grab a collection in a custom view. It requires a path, and a 'schemaResolver'. I cannot work out from the documentation, exactly how to generate a schemaResolver. I have a schema, I have a collection, and I have attempted to use a function according to the type 'EntitySchemaResolver', but this requires parameters of 'entityID', and some values. Since I am fetching a collection, there is no particular entityID, and I have no values to pass either. I understand that some built properties on a schema might need to be resolved, but is there a function I can use to do this, and if not, how does one actually create a functioning schemaResolver, that I can pass to useCollectionFetch? Thank you.

**Comment by jabelone** [comment]
I just had a very similar issue and finally worked it out, so thought I'd post how here in case anyone else finds it :)

```
    // grab the firecms navigation context
    const navContext = useNavigation();

    // build an EntityCollection
    const testCollection = buildCollection({
        path: "path-to-collection",
        schema: collectionSchema,
        name: "Collection",
    });

    const collectionResolver = navContext.getCollectionResolver("path-to-collection");

    if (!collectionResolver) throw Error("Collection resolver is undefined!!!");
    const { schemaResolver } = collectionResolver;
```
