### ISSUE TITLE
Click on AdditionalView menu does not close the drawer

### ISSUE THREAD

**Issue by fabarea** [Camberi/firecms#24]
I am implementing some additional views to add custom "panels" for the end users. When clicking the menu, it should close the drawer as for the other menu titles. Furthermore, it would be nice to equally format the menu title => make it uppercase as for the rest.

```

ReactDOM.render(
    <CMSApp
        ...
        additionalViews={[
            statisticsView,
        ]}
        ...
    />,
    document.getElementById("root")
);
```

Version of FireCMS: 

```
"@camberi/firecms": "^0.18.0",
```

<img width="743" alt="image" src="https://user-images.githubusercontent.com/620730/100861502-34c30e00-3492-11eb-84d6-1d2e7ea3dd8c.png">

**Comment by fgatti675** [comment]
Fixed in 0.19.0 :)
