### ISSUE TITLE
Can a search field be added to drop-down lists?

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#243]
Hi
We have in some collections really long drop-down lists (reference to other collections). It would be useful to have a search field to narrow the displayed items in the list. As I understand firecms does not support it, however, do you have a recommendation how we could solve this? thanks

**Comment by fgatti675** [comment]
For references to other collections, you can add text search using a 3rd party service as Algolia.
You need to index your data externally, probably using cloud functions.
There are additional instructions here: https://firecms.co/docs/firebase_cms_app#text-search
