### ISSUE TITLE
Module title does not correspond in AdditionalViews

### ISSUE THREAD

**Issue by fabarea** [Camberi/firecms#25]
Module title does not correspond for AdditionalViews as for the "regular" views.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/620730/100862387-65f00e00-3493-11eb-927d-fcea9bf0a17f.png">

**Comment by fgatti675** [comment]
Fixed in 0.19.0 :)

**Comment by fgatti675** [comment]
Ok, now fixed for good in 0.23.0 :)

**Comment by fabarea** [comment]
Thank you very much!
