### ISSUE TITLE
Cannot find module '@camberi/firecms' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by makifakkaya** [Camberi/firecms#250]
```
Cannot find module '@camberi/firecms' or its corresponding type declarations.ts(2307)
```

This error is in the App.tsx file

<img width="893" alt="image" src="https://user-images.githubusercontent.com/60367291/156824426-911fdfd7-9527-4a6c-9bfb-779a7660ad23.png">

**Comment by fgatti675** [comment]
Did you run `yarn install`?

**Comment by makifakkaya** [comment]
> Did you run `yarn install`?

yes i think i did everything but i couldn't solve this error

**Comment by fgatti675** [comment]
This seems to work fine using the quickstart, must be a problem with your setup
