### ISSUE TITLE
List view doesn't show snackbar prompts(onPresave). Disabling inlineEditing doesn't refresh the document that you have updated

### ISSUE THREAD

**Issue by jbethuel** [Camberi/firecms#253]
As always, thanks for the awesome package 🎉

**Comment by fgatti675** [comment]
Hi @jbethuel thanks!
I have fixed the inlineEditing issue.
The snackbar onPreSave seems to work fine though?

**Comment by jbethuel** [comment]
Apologies, it is when you edit the document in list/table view. @fgatti675

**Comment by fgatti675** [comment]
Couldn't reproduce this issue in the latest version.
Feel free to reopen if neccesary!
