### ISSUE TITLE
filtered data by uid

### ISSUE THREAD

**Issue by woosuk288** [Camberi/firecms#265]
Hi, I would like to make users read the firestore data they only created.

for example, there are users A and B.
two firestore data are
`  
  {
     name: 'apple',
     uid: 'A',
  },
  {
     name: 'tomato',
     uid: 'B',
  }
`
A has to read A's data. A's data must not be shown to B
B has to read B's data. B's data must not be shown to A

I've tried initialFilter of buildCollection to implement this but I couldn't

how can I resolve this?

Thank you

**Comment by fgatti675** [comment]
Hi @woosuk288 
I am afraid this is not possible at this time. You could change the `initialFilter` based on the user id, using a NavigationBuilder, but the users could still  change the filter manually.
We will consider this use case for the future

**Comment by andrashee** [comment]
Hi all,
Foremost, thanks a lot for this really great project!
We would also love to have the option to filter down a collection based on conditions. Similarly to https://github.com/Camberi/firecms/issues/188 
Having this feature could extend the use cases where one can use firecms quite significantly: not just for data management by internal administrators, but also e.g by external clients.

Are you planning on adding this soonish? Would you be open to PRs?

**Comment by fgatti675** [comment]
Hi @andrashee 
We are definitely open for PRs! They are encouraged, since our focus right now is on working on version 2 of the CMS.
I think it makes sense to provide a prop other than `initialFilter`, with the same format.
Maybe just a prop called `filter`, that when set forces filtering by it, and disables filtering and sorting for the view

**Comment by fgatti675** [comment]
You can use now the prop `forceFilter` in collections for this exact purpose, in the latest v2.0.0 versions

**Comment by andrashee** [comment]
That's great, works like a charm. Thanks!

**Comment by fgatti675** [comment]
@andrashee welcome!

**Comment by handihow** [comment]
Getting to know your awesome FireCMS system. I am quite impressed.
Is there an example of this in the documentation? How can you get the user's uid and use it in the forceFilter?
Thanks
