### ISSUE TITLE
Filter by nested fields

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#266]
Hi there!

I hope you are doing well! Every time I come back to this project, it's awesome to see all the updates!

I am not sure if this is a feature request or already possible but I would like to filter a collection by nested fields. For example, I have an entity with the following fields in firebase:
```
config: {
  filters: {
    publish: true,
    free: false
  }
}
```

Is there a way I could have a filter in the collection view such that I only see entities with config.filters.publish == true or false? Firestore supports querying by nested fields so it shouldn't be an issue with firestore queries on that.

If it is not possible using the filterCombinations field in EntityCollection, is there a workaround; for instance, through a button in the extraActions component?

If this is not at all possible, will be great to have it in the future! :)

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi 
This it not possible at the moment but will add it as a feature request
Thanks a lot for your nice words :)

**Comment by faizanabidnaqvi** [comment]
Hey, thanks for getting back!

I think an additional related feature request will be to support showing nested fields in collection view. I know that is possible by creating additional columns but it will be nice if we can just include a nested field in the 'properties' value for the collection like 'config.filters.publish' and the cms renders the nested field with the correct widget and filter options if it is a primitive field like boolean, string, or number.

**Comment by fgatti675** [comment]
Forgot to mention, in the latest versions of 2.0, you can now use the prop `spreadChildren` in map properties, which generates a column per child property. You can also use that feature for fitlering!

**Comment by joestephens** [comment]
@fgatti675 Please would you be able to provide an example of the correct way to filter the `spreadChildren` columns?

I have the below:
```js
const usersCollection = buildCollection({
  path: 'users',
  initialSort: ['firstName', 'asc'],
  forceFilter: {
    tutor: ['==', true],
  },
  properties: {
    firstName: buildProperty({
      name: 'First Name',
      validation: { required: true },
      dataType: 'string',
      columnWidth: 300,
    }),
    lastName: buildProperty({
      name: 'Last Name',
      validation: { required: true },
      dataType: 'string',
      columnWidth: 300,
    }),
    customClaims: buildProperty({
      dataType: 'map',
      spreadChildren: true,
      properties: {
        admin: buildProperty({
          name: 'Is Admin?',
          dataType: 'boolean',
          readOnly: true,
        }),
        tutor: buildProperty({
          name: 'Is Tutor?',
          dataType: 'boolean',
          readOnly: true,
        }),
      },
    }),
  },
  name: 'Users',
  // eslint-disable-next-line @typescript-eslint/no-shadow
  permissions: ({ authController }) => ({
    edit: false,
    create: false,
    delete: false,
  }),
  inlineEditing: false,
  group: 'Student Operations',
});
```

But the `forceFilter` property gives a TypeScript error, and once saved I get an error in FireCMS: "Order by clause cannot contain a field with an equality filter tutor".

Any help is greatly appreciated, thank you.

**Comment by fgatti675** [comment]
I think there are a couple of things here.
Firestore does not allow to have one filter set, and order by a different one, like you are doing here. 'firstName' and 'tutor'
I can't test this right now, but I think the syntax for the filter would be 
```
  forceFilter: {
    "customClaims.tutor": ['==', true],
  },
 ```

**Comment by joestephens** [comment]
I forgot to confirm on this one, but that worked a treat @fgatti675 - seems I was just trying the wrong combinations! Thank you very much for your assistance ❤️
