### ISSUE TITLE
Use of deprecated useAuthContext() in example custom view?

### ISSUE THREAD

**Issue by jabelone** [Camberi/firecms#275]
Hey there,

I've been pulled into a firecms project and have been implementing a custom view as we need to use a collection group query which doesn't appear to be supported out of the box. I was following https://firecms.co/docs/custom_top_level_views/, but was a little confused where `useAuthContext()` was coming from in the example view. It looks like it has been renamed to `authController()` recently and perhaps that example page hasn't been updated since then?

I've done a simple PR in #274 to update the example, but I don't know firecms well enough to determine if this is the right way to do it.

Cheers!

**Comment by fgatti675** [comment]
Thanks for the catch! Merged and being deployed,
you are right it was renamed but there was an error in the docs
