### ISSUE TITLE
yarn add not working

### ISSUE THREAD

**Issue by dvird** [Camberi/firecms#280]
https://firecms.co/docs/quickstart/

when running on terminal:

yarn add @camberi/firecms firebase@^9 @mui/material@^5 @mui/icons-material@^5 @mui/lab @mui/styles@^5 @emotion/react @emotion/styled react-router@^6 react-router-dom@^6

zsh: no matches found: firebase@^9

**Comment by fgatti675** [comment]
That's weird, seems to work for me, and no one has reported this before. 
Do you have the latest `yarn` version?

**Comment by dvird** [comment]
i removed the versions like : @^9  and it worked
