### ISSUE TITLE
Sort icons are backwards

### ISSUE THREAD

**Issue by 5hee75** [Camberi/firecms#289]
I noticed that sorting columns in the tables seems to be using the opposite arrow direction than what is typical/expected.  The standard is for the "up" arrow to mean 'asc' and "down" arrow to mean 'desc', but this seems to be flipped in `firecms`.  See screenshots for illustration.

Sort in `firecms` - note how values are going from high to low while the arrow points up.

![image](https://user-images.githubusercontent.com/24514558/162557921-5024fb12-2bd7-4e6d-9be3-e041550b8851.png)

Sort in `mui` datagrid docs - note how values go from low to high
![Screen Shot 2022-04-09 at 1 28 12 AM](https://user-images.githubusercontent.com/24514558/162557874-b671f80a-2a02-4486-b43a-7b871f3d2c1f.png)

**Comment by fgatti675** [comment]
You are right! 
Changed that behaviour in version 1.0.0-rc5
