### ISSUE TITLE
FirebaseConfig is being logged in production?

### ISSUE THREAD

**Issue by nathanieldeal** [Camberi/firecms#294]
Hello, I have a question about this line in https://github.com/Camberi/firecms/blob/9dfd9d06ca8ac2512934f159e4412d7995c60e00/src/firebase_app/hooks/useInitialiseFirebase.ts#L59

It always logs our firebaseConfig on page load, which is available to everyone that uses the app.

Is there a specific reason why this is here, particularly on production?

Thanks!

**Comment by nathanieldeal** [comment]
Awesome thanks for the fast response. I would really appreciate if you could make that update in the next release. Keep up the great work!

**Comment by fgatti675** [comment]
Fixed a few releases ago!
