### ISSUE TITLE
When sorting by a column then filter is lost

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#298]
Hi
We some time ago opened this support request https://github.com/Camberi/firecms/issues/151, it was then closed. Now we tried to implement your recommendations, however it does not work. Can you help what we are doing wrong?

The problem: 
1: I apply a filter on column (MeditationID)
2: Then I sort by another column (UpdateDate)
Result: The filter is lost.

We have set the filter as follows.
![grafik](https://user-images.githubusercontent.com/65586807/163533277-6110258f-2325-45d9-b1ff-352373b5b425.png)

and the index as follows:
![grafik](https://user-images.githubusercontent.com/65586807/163533328-6cd0be60-c7d6-4f27-93f7-ec359e8ac231.png)
Do you have an idea why it does not work?

thanks!

**Comment by Andre3424** [comment]
hi @fgatti675 hope you are well! could you take a look at the question above, this would be great, thanks!

**Comment by fgatti675** [comment]
Hi @Andre3424 
There seems to be a bug in the code that we are fixing, but in any case, you can't filter by a property and sort by another one unfortunately.
Firestore has some weird limitations in this sense:
https://firebase.google.com/docs/firestore/query-data/order-limit-data
We are fixing the bug for the final release 1.0.0

**Comment by Andre3424** [comment]
hi @fgatti675 thanks for your feedback and the link. According the link it seems to me it should be possible to filter and sort, no? Or is the problem that when we sort in FireCMs it queries again firestore? We cannot sort in firecms a resultset we retrieved?

**Comment by fgatti675** [comment]
This bug should be fixed in the latest version 2 alpha!
