### ISSUE TITLE
"EntityCollectionView" is not exported from '@camberi/firecms'

### ISSUE THREAD

**Issue by altechzilla** [Camberi/firecms#3]
When trying to run this, it says "EntityCollectionView" is not exported from `'@camberi/firecms'`. Any thoughts @fgatti675 fgatti675? Thank you!

```
import React from 'react';
import { CMSApp, EntityCollectionView, buildSchema } from '@camberi/firecms';
import { requireAuth } from 'util/auth.js';

import products from './data/schemas/products.json';
import locales from './data/schemas/locales.json';

function Admin(props) {
	return (
		<CMSApp
			name={'CMS'}
			authentication={() => {
				return true;
			}}
			navigation={
				<EntityCollectionView
					relativePath="products"
					schema={buildSchema(products)}
					name="Products"
					subcollections={[
						{
							name: 'Locales',
							relativePath: 'locales',
							schema: buildSchema(locales),
						},
					]}
				/>
			}
			firebaseConfig={{
				apiKey: '',
				authDomain: '',
				databaseURL: '',
				projectId: '',
				storageBucket: '',
				messagingSenderId: '',
				appId: '',
				measurementId: '',
			}}
		/>
	);
}

export default requireAuth(Admin);

// TODO: Restrict to admin users only.
```

**Comment by fgatti675** [comment]
Hi @altechzilla,
`EntityCollectionView` is a TS interface, not a React Component. You simply use it as an object. Try the code bellow :)
Actually `EntityCollectionView` is probably not the best name and I understand the confusion, feedback welcome!

`import React from "react";
import { buildSchema, CMSApp } from "@camberi/firecms";
import { requireAuth } from "util/auth.js";

import products from "./data/schemas/products.json";
import locales from "./data/schemas/locales.json";

function Admin(props) {
    return (
        <CMSApp
            name={"CMS"}
            authentication={() => {
                return true;
            }}
            navigation={[
                {
                    relativePath: "products",
                    schema: buildSchema(products),
                    name: "Products",
                    subcollections: [
                        {
                            name: "Locales",
                            relativePath: "locales",
                            schema: buildSchema(locales)
                        }
                    ]

                }
            ]}
            firebaseConfig={{
                apiKey: "",
                authDomain: "",
                databaseURL: "",
                projectId: "",
                storageBucket: "",
                messagingSenderId: "",
                appId: "",
                measurementId: ""
            }}
        />
    );
}

export default requireAuth(Admin);

// TODO: Restrict to admin users only.`

**Comment by altechzilla** [comment]
Great, thanks!
