### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#30]
Is there a way to override the Mui theme being used in the project? This is not really an issue but it will be super cool to be able to customize the theme! :)

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi,
currently theming is limited to changing the primary and secondary color and font family.
https://github.com/Camberi/firecms/blob/master/src/CMSAppProps.tsx
Before allowing to override the theme we would need to go through all the code and change every hard coded style!

**Comment by faizanabidnaqvi** [comment]
Hey @fgatti675 

Thanks for pointing it out and this seems sufficient for basic needs.

I understand some styles are hardcoded, but will it be possible to wrap the CMSApp in our own MuiThemeProvider? That way, we can modify any default styles; although I do understand it might not affect any hardcoded styles. This is just a nice to have.

**Comment by fgatti675** [comment]
Full theme override is now possible  in version 1.0.0-beta1 :)
