### ISSUE TITLE
keep empty collectiond

### ISSUE THREAD

**Issue by NoamMuallem** [Camberi/firecms#301]
Hi I have a firecms set up for my gatsby project, the problem, is that on build, I cannot have empty collections, but after deleting the last doc in a collection, the collections is deleted and thats crashes my build process.
There is an option anywhere to keep empty collections on firestore?

**Comment by fgatti675** [comment]
Sorry I don't think I understand. Can you explain with a bit more detail?

**Comment by NoamMuallem** [comment]
When you delete the last document in a collection, the collection is being deleted, I need an empty collection instead, is there a way to do it?

**Comment by fgatti675** [comment]
Hi @NoamMuallem 
As far as I know there is no way, but since it is Firestore question you may want to ask in a specific forum.
In any case, I would build my pipeline in a way that it supports non existing collections
