### ISSUE TITLE
Error on array of timestamp data types

### ISSUE THREAD

**Issue by tijnar** [Camberi/firecms#31]
I want to store array of timestamps in cloud firestore. I can add new item to the database by using below code. But during the preview in the table of the collection in firecms it is giving me error. 
my code:

available_dates: {
            dataType: "array",
            title: "Available Dates",
            validation: {
                required: true
            },
            of:{
                dataType: "timestamp",
            }
            
        },

**Comment by fgatti675** [comment]
Fixed in 0.20.0 :)
