### ISSUE TITLE
Is there a way to set storage path based on entityId for new document?

### ISSUE THREAD

**Issue by xeonicca** [Camberi/firecms#313]
Hello, first of all thank you for making this cms as it helps out greatly in my project :D

I wonder if there is any way to use entityId as storage path for a new document?
Using the `storagePath` as function, I was able to get `context.entityId`, but unfortunately it is empty as document is not created yet.
So my next question is, is there any way to create a system generated id as `customId` ?
Then I will be able to access the id with `context.values.customId`, however from what I understand, this value is input by user.

**Comment by corvinav** [comment]
I have the same questions. I found this thread https://github.com/Camberi/firecms/issues/64 it's an acceptable solution, but I would like to have something like this:
`
storagePath: function (entityId) {
              return `images/${entityId}`,
            },
`

@fgatti675  Maybe it's possible to set custom entityId and get it from some generator or better from firestore.collection.doc() (as I know it generates  proper document id for a new document in collection) Is it possible to get this function from firebase when I describe scheme and then get this custom entityId in the storagePath function or file name?

ps thank you for the cool lib. Also sorry if I asked a stupid question - I'm an android developer, and I'm creating a mobile application for Ukraine as a volunteer and need to create a simple admin module for it. So I have very low experience in web development.

**Comment by fgatti675** [comment]
Hi guys, this issue has been solved for version 2.0.0, which is currently in alpha though!
There are no docs yet but we are working on them.
If you really need this, you can give it a try.
But be aware that there might be breaking changes down the line
