### ISSUE TITLE
Integrate Algolia Search

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#318]
Hi Francesco
we want to install and integrate Algolia Search. You once sent this link https://firecms.co/docs/firebase_cms_app#text-search, but this does not work anymore and I did not find it. Does it somewhere still exist?

Should we simple install this extension https://www.algolia.com/developers/firebase-search-extension/#three-steps?

thanks!

**Comment by fgatti675** [comment]
Hi Andre, the link is back :)
I have never used the extension but it is probably the best way to ingrate Algolia right now
