### ISSUE TITLE
yarn check displays many dependencies errors

### ISSUE THREAD

**Issue by fabarea** [Camberi/firecms#32]
Hi,

I just pulled the latest commit #910711a7b196. It looks there are many dependencies errors that can be seen with command `yarn check`. If not all them are easily fixed perhaps one could reduce the list.

FYI, I had tiny differences of visual by using `npm install && npm run start` most probably because of the dependency resolution when facing dep. issues.

**Comment by fgatti675** [comment]
I've managed to reduce the errors to 14 in version 0.21.0, way less than before.
Many errors are related to dependencies not ready for React 17
