### ISSUE TITLE
Quickstart  guide installation Error

### ISSUE THREAD

**Issue by Prottoy2938** [Camberi/firecms#320]
I've followed the Firecms installation guide but getting this error when I try to run the app

![alt text](https://i.ibb.co/KLdXHJx/Screenshot-11.png)

My Code: https://github.com/Prottoy2938/lenin-cms

**How do I run the app properly?**

**Comment by fgatti675** [comment]
Hi, are you on version 1 or 2 of FireCMS?

**Comment by Prottoy2938** [comment]
Version 1.0.0

**Comment by Prottoy2938** [comment]
If anyone could give me a link of a working quickstart repository of this project on GitHub, that'll be enough.

**Comment by fgatti675** [comment]
Thanks for the catch @Prottoy2938 
We mixed up the quickstart of both versions, should be fixed now!

**Comment by Prottoy2938** [comment]
Version 1.0
