### ISSUE TITLE
Custom document ID based on document values

### ISSUE THREAD

**Issue by dhazeley** [Camberi/firecms#325]
When defining an [EntitySchema](https://firecms.co/docs/entities/entity_schemas/) you can use the `customId` field to control the behavior of setting the document's ID on creation.

Is there a way to set the ID of the document on save, based on the values given? For example:
I have a `Users` collection and `Memberships` collection. `Membership` documents have a `userRef` field which is a reference to a `User` document. When creating a `Membership` document, I want to set the ID of the `Membership` document to be the id of the attached `User` document.

**Comment by Timu5** [comment]
There is a way, in onSaveSucess callback I'm deleting entity and creating new new with specific id like that:
```js
       await context.dataSource.deleteEntity({
            entity: {
                id: entityId,
                path: path,
                values: values
            }
        });

        await context.dataSource.saveEntity({
            entityId: myNewSuperId,
            path: path,
            values: values,
            collection: UserCollection,
            status: 'new'
        });
```

**Comment by dhazeley** [comment]
> There is a way, in onSaveSucess callback I'm deleting entity and creating new new with specific id like that:
> 
> ```js
>        await context.dataSource.deleteEntity({
>             entity: {
>                 id: entityId,
>                 path: path,
>                 values: values
>             }
>         });
> 
>         await context.dataSource.saveEntity({
>             entityId: myNewSuperId,
>             path: path,
>             values: values,
>             collection: UserCollection,
>             status: 'new'
>         });
> ```

This the workaround I ended up implementing

**Comment by fgatti675** [comment]
Hi guys, there is a new hook you can use in version 2.0.0 to update the document id dynamically based on other values:
https://firecms.co/docs/collections/callbacks/
so you don't need to rely on hacks
