### ISSUE TITLE
[v2.0.0] Can't select text inside dialog

### ISSUE THREAD

**Issue by ciriousjoker** [Camberi/firecms#331]
I can move the dialog by leftclick+drag anywhere in the dialog. Sadly, even though the cursor changes correctly inside the textarea, leftclicking still drags the window instead of selecting the text.

### Workaround
- Click on first location
- Shift-click on second location to select everything in between

### Versions tested
- `2.0.0-alpha.15`

<details>

<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/16866223/173843304-db4b8e1d-fdc2-480e-a08d-021567cb9d4b.png)

</details>

**Comment by fgatti675** [comment]
This is fixed in the latest alpha version ;)
