### ISSUE TITLE
Firebase: Error (auth/unauthorized-domain) 

### ISSUE THREAD

**Issue by zakblacki** [Camberi/firecms#332]
So I'm trying to integrate this with my on going project preproduction,
I've tried following documentation and login with google, got error so I'm assuming we cannot use this locally. (neither shared hosting)
so it would be nice to mention this as well in the docs for OAuth. even a video for setup this would benefit us all.

**Comment by fgatti675** [comment]
You can add `localhost` to your authorized domains in your auth config in Firebase
