### ISSUE TITLE
firecms.co Website Triggers Antivirus for Trojan Horse

### ISSUE THREAD

**Issue by ckoegel** [Camberi/firecms#334]
While looking thru the [Docusaurus Showcase](https://docusaurus.io/showcase), I noticed your site(firecms.co) and wanted to check out your page since it appeared as though you have redone the Docusaurus default landing page. After clicking on the link, my company antivirus prevented me from loading the site and I received the notification attached.
![firecms](https://user-images.githubusercontent.com/53310569/176198252-7a191ec8-85df-4623-9d5d-dd2c54dc5ca6.PNG)
After googling the JS/CoinMiner, I found a Microsoft page classifying it as a trojan horse virus. I reported this to the people at Docusaurus, who say they check websites before they are allowed in the showcase, which seems to imply this occurred after being added to the showcase. I was hoping someone could provide some clarification or an explanation as to why this issue might have arose, and to see if this can be investigated further, thank you.

**Comment by fgatti675** [comment]
Hi, can you confirm this is still happening?

**Comment by ckoegel** [comment]
As of 8/5/2022 this is no longer happening

**Comment by fgatti675** [comment]
Thank you!
