### ISSUE TITLE
Creating a document with subcollections - always must open a 2nd time

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#336]
Hi Francesco
A question about creating documents with subcollections in firemcms. Maybe we are doing something wrong, but the way it is, it is now quite "painful" work. We have a colleciton with some main fields in root and language fields in the language subcollection.
What I do
1: Create new document and fill the main fields
2: Now I would like to add language subcollection. But this is not possible, because as it seems document first must be saved. So I save the document, but as result document editform closes completely
3: Now I have to search in the long list of documents again my just created new document, click edit and now I can add language subcollection.

Am I doing something wrong? Is there an easier way?
thanks!

**Comment by Andre3424** [comment]
@fgatti675 thats great thanks!
when is the next release planned?

**Comment by fgatti675** [comment]
This behaviour has been changed in the last 2.0 version
