### ISSUE TITLE
Unexpected value error shown for on_update timestamp field and it gets set without changing anything

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#34]
Hi there!

I tried using the timestamp property with auto value set to "on_update". The field gets set correctly if I do make changes to the item and save.

However, if I open an item, don't change anything, and then press save, it throws an error in the on_update field. 

<img width="308" alt="Screenshot 2020-12-15 at 11 51 53 AM" src="https://user-images.githubusercontent.com/5749036/102206443-ec154700-3ecc-11eb-9943-a830dedae550.png">

Additionally, the browser prompts me that I have unsaved changes even though I did not make any changes. On this popup, if I press discard, it still saves timestamp with the updated timestamp set. Ideally, I think if we save an item without making any changes it should not save the item or make changes to the on_update fields.

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi ! Can you check if this is solved in version 0.20.0 ?

**Comment by faizanabidnaqvi** [comment]
Hi @fgatti675 

Thanks for the response! :) I just checked. It's not fixed yet.

**Comment by fgatti675** [comment]
Ok, so there is been a lot of updates in version 0.21.0 and it seems to be working fine, can you check now? :)

**Comment by faizanabidnaqvi** [comment]
Hi @fgatti675 

Apologies for the late response! I updated to the latest version 0.22.0 and checked.

So now, I don't get the error which is awesome :) and works! BUT the updated timestamp value still changes even if I didn't make any changes at all. As a suggestion, I think if we press save on an item without touching or modifying any field in it, it should not actually save or update the timestamp. 

Just a suggestion! And great work here! The new version is so much better. :D

**Comment by faizanabidnaqvi** [comment]
The feature where the save button is disabled unless any changes are made kind of resolves this!
