### ISSUE TITLE
Modify data after fetching but before displaying

### ISSUE THREAD

**Issue by Timu5** [Camberi/firecms#342]
Is seems like is not possible to modify data from firebase before displaying, Am I correct?

Example scenario:
- Data in firebase stored in unusual way, and need to be converter before displaying so that one can use FireCMS advantages.

Possible solution:
- Add `onPostFetch` callback the same way as `onPreSave` therefore we can modify data on fetching and on saving.

**Comment by fgatti675** [comment]
Hi @Timu5 that sounds good.
Would you like to give it a try?

**Comment by Timu5** [comment]
Sure, I will give it a try

**Comment by fgatti675** [comment]
Hi @Timu5 
This has been released in the last version but renamed to `onFetch`
Thanks!!
