### ISSUE TITLE
Critical Issue for Saving Values

### ISSUE THREAD

**Issue by ssandino** [Camberi/firecms#348]
`Bug` // We first discovered it in our own admin tool running on FireCMS (`2.0.0-alpha.22`). If two values in same collection are changed (within proximity in time) then something strange happens.

Specially critical when used with number fields, as the numbers are almost randomly changed in the database (and hard to notice for user). 

I was able to reproduce the issue directly in the FireCMS Demo:
![bug3](https://user-images.githubusercontent.com/6095849/180978200-6a5bad30-a09b-4366-93aa-f245a6e58b2f.gif)

This seems unrelated to what browser or operating system is used.

**Comment by fgatti675** [comment]
Hi @ssandino 
We have reworked how values are saved in the latest alpha 2.0 version and this should be fixed.
Thanks for the catch!

**Comment by ssandino** [comment]
👏 thx
