### ISSUE TITLE
Is it possible to build preview of images from external source

### ISSUE THREAD

**Issue by Zimmee** [Camberi/firecms#359]
I'm interested in displaying images from external url(not Firebase storage). I don't need the upload functionality. So is it currently possible to do, without using custom preview?

**Comment by fgatti675** [comment]
This is possible in version 1.0 but not yet in version 2.0
Adding it as a feature request

**Comment by fgatti675** [comment]
Hi, this has been added in 2.0.0-alpha.27 :) Just set the `url` value to `image` or `video` instead of a boolean
