### ISSUE TITLE
Can I disable the user from adding new document to the collection?

### ISSUE THREAD

**Issue by tijnar** [Camberi/firecms#36]
I just want to view all the documents of firestore in the cms, but I want to disable the user from adding new documents to the collection. How can i do this ?

**Comment by fgatti675** [comment]
Hi @tijnar, in version 0.21.0 you can set the flag `editEnabled` to false in the collection level
Let me know if that works out for you

**Comment by tijnar** [comment]
@fgatti675 in the new update I am able to do inline editing when it is true. But i am not able to edit in side panel. Side panel is not popping what ever the value of inlineEditing.

**Comment by fgatti675** [comment]
Hi @tijnar 
Can you try in version 0.21.2 ?

**Comment by tijnar** [comment]
@fgatti675 its working now. But what if  I want to enable the editing of existing document but disable adding of new document in the collection.

**Comment by fgatti675** [comment]
Hi @tijnar 
We have revamped the permissions system in version 0.30.0 and now you can prevent users from creating new entries :)
