### ISSUE TITLE
Unexpected value: {} for on_create timestamp

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#360]
Hi @fgatti675 

There is a new issue that has been occurring in v1.0.0 for me. I have an entity with the on_create timestamp field that is already set. The field is as follows:
```
createdOn: {
            dataType: "timestamp",
            title: "Creation Date",
            disabled: true,
            autoValue: "on_create"
        },
```

When I make changes to the entity and press save, I get this 'Unexpected value: {}' message under the 'Created Date' field and the 'Unsaved changes' popup shows up. If I press the Ok' button from there, the entity does get saved correctly. It is annoying in cases where our users have to update several entities and have to press 'Ok' to this popup every time.
<img width="510" alt="Screenshot 2022-08-10 at 3 58 30 PM" src="https://user-images.githubusercontent.com/5749036/183908253-15725911-abba-45b0-bd1d-e87097268357.png">

Also note that if we press 'cancel' on the unsaved changes popup, the dialog stays open and if we press save once again from there the 'createdOn' field gets saved as a map with '{}' value.

I didn't see this issue in some previous versions but I don't remember which version this exactly started happening on.

**Comment by faizanabidnaqvi** [comment]
This issue happens with 1.0.2 as well. I also noted that the issue will occur with all kinds of 'timestamp' fields, even those which are not auto value.

It doesn't happen with 1.0.0-rc05.

**Comment by faizanabidnaqvi** [comment]
I had a new issue with 1.0.0-rc05 not showing anything at all after I upgraded dependencies and deleted yarn.lock. However, when I use 1.0.3-pre.2 it worked.

This issue (unexpected value for dates) didn't occur in 1.0.3-pre.2 but it was occurring before so I think it was something to do with yarn.lock. So if anyone faces this issue, I think upgrading dependencies and deleting yarn.lock, and reinstalling should fix it.

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi , 1.0.3 has been released :)
