### ISSUE TITLE
Password login broken (2.0.0-alpha.25)

### ISSUE THREAD

**Issue by mkue** [Camberi/firecms#361]
After upgrading from `2.0.0-alpha.22` to `2.0.0-alpha.25` it seems that the password login does not work anymore.

See video:

https://user-images.githubusercontent.com/3518809/184477875-59196c69-1904-4156-94d7-2f822891b577.mp4

If I downgrade to `2.0.0-alpha.22` it works again. Thanks for looking into this🙏🏼

**Comment by fgatti675** [comment]
Thanks for the catch!
Fixed in version `2.0.0-alpha.26`
