### ISSUE TITLE
Update boolean data with FireCMS

### ISSUE THREAD

**Issue by tjsummour17** [Camberi/firecms#363]
Hello,

When I was trying to update boolean data via FireCMS it was not do anything from dashboard directly (Direct Records)
It was only working when I open the side menu to update from there

Please find the attachment:
https://user-images.githubusercontent.com/55631161/184537776-2aa99748-3a5b-4690-9ebb-76b44e7b048b.mov

<img width="641" alt="Screen Shot 2022-08-14 at 15 53 47" src="https://user-images.githubusercontent.com/55631161/184537842-6bc9f7a4-ea31-46fb-92e0-82a4c1a3966c.png">

<img width="2039" alt="Screen Shot 2022-08-14 at 15 54 55" src="https://user-images.githubusercontent.com/55631161/184537896-c4999cd2-0e27-4869-96d4-52643c437c0f.png">

**Comment by fgatti675** [comment]
Hi @tjsummour17 what version of FireCMS are you using?

**Comment by tjsummour17** [comment]
@fgatti675 v 1.0.2

**Comment by fgatti675** [comment]
Hi @tjsummour17 
I think this error is due because you have some references in your data that are not mapped in your collection.
This is a bug in version 1.0 that is fixed in version 2.
You can either update to version 2, or try mapping all the references in your collection.
Cheers
