### ISSUE TITLE
Disabling InlineEditing is stoping table from updating

### ISSUE THREAD

**Issue by Timu5** [Camberi/firecms#364]
After setting `inlineEditing: false` and editing field in sidebar after clicking save(or save and close) value in table is not being refreshed. Only after sorting table or page reload new value is shown.

Tested on: 2.0.0-alpha.24  and 2.0.0-alpha.26

**Comment by fgatti675** [comment]
Hi, this should be fixed in version `2.0.0-alpha.27`
