### ISSUE TITLE
Content DnD Error

### ISSUE THREAD

**Issue by benharvey1213** [Camberi/firecms#368]
I followed the [building a blog](https://firecms.co/docs/recipes/building_a_blog) tutorial, but I noticed that drag-n-drop module re-ordering does not work. Getting a react-beautiful-dnd error on drag.

![image](https://user-images.githubusercontent.com/45473836/186502372-661a4751-0534-48e5-9662-d5ac76e1033d.png)
![image](https://user-images.githubusercontent.com/45473836/186502384-f10d4d73-c117-40d2-a528-f898c0ea5f6a.png)

**Comment by benharvey1213** [comment]
Turned out to just be a React issue. https://stackoverflow.com/questions/67780314/react-beautiful-dnd-invariant-failed-cannot-find-droppable-entry-with-id

**Comment by fgatti675** [comment]
Awesome, thanks!
