### ISSUE TITLE
Sortable collection

### ISSUE THREAD

**Issue by DominikBB** [Camberi/firecms#369]
Potential enhancement which would allow a user to sort a collection in by manually reordering entries.

## Example
An e-commerce site has a category menu, a user would like to sort the order of category items in a specific way.

## How could this be achieved
Adding drag and drop to rows, with some kind of index metadata in a document.

**Comment by fgatti675** [comment]
Hi @DominikBB 
This is a big change.
It would be a nice addition but we would need quite some effort to make it work.
I am closing this ticket for now.
If you are interested in treating this feature as a consulting project, don't hesitate to contact us at hello@camberi.com :)
