### ISSUE TITLE
Allow image resizing on upload

### ISSUE THREAD

**Issue by fgatti675** [Camberi/firecms#37]
Implement and expose the API
Candidate: https://gist.github.com/SagiMedina/f00a57de4e211456225d3114fd10b0d0

**Comment by osmankh** [comment]
Hello @fgatti675, 
First Big Thanks for you and all the contributors for building this awesome cms!
I just need to know if there is any updates/ways to compress and resize images before upload. Is their a plan to add this feature? if not can you please just guide me how can I work around to achieve it!
Thanks again.

**Comment by osmankh** [comment]
Any updates on this?

**Comment by fgatti675** [comment]
Hi @osmankh 
Sorry, I can't give you an estimate for this ticket since we have some others in the pipeline.
If you would like to give this a try, you can try to implement your own custom Field:
https://firecms.co/docs/custom_fields
For reference, the current field that is used for storage is:
https://github.com/Camberi/firecms/blob/master/src/form/fields/StorageUploadField.tsx
If you make it work, please share with me your implementation so we can merge it into the core of the library

**Comment by jamiegalbreath** [comment]
OOh would love this

**Comment by fgatti675** [comment]
Added in latest v2 version
