### ISSUE TITLE
Adding a button with some logic for each record

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#373]
hi!
A question: We want to add a button in each row of our products, to illustrate here a screenshot from your demo
![grafik](https://user-images.githubusercontent.com/65586807/188650175-30fde436-a2ff-4563-a345-ae3e69a140f8.png)

When the user clicks the button, then some should be executed with the record (in the screenshot "Baseball Cap"): We show a popup and the user can choose a target category where the current record is duplicated and assigned.

According our developer this is not easy to implement (button is easy, but logic with reading "Baseball Cap" record and something with it not). You have maybe some example or reference to the help section, which could help us doing this task?
thanks!

**Comment by Andre3424** [comment]
@fgatti675 hi Francesco, could you take a short look at the question above? thanks

**Comment by fgatti675** [comment]
Hi @Andre3424 sorry for the late reply.
You can do this with an additional column!
I think the only thing you can't do is to order that additional column in between other properties

**Comment by Andre3424** [comment]
@fgatti675 thanks! We will check once more

**Comment by Andre3424** [comment]
@fgatti675 that's great, thanks!
