### ISSUE TITLE
Can't use authController.setExtra inside useValidateAuthenticator 

### ISSUE THREAD

**Issue by joestephens** [Camberi/firecms#374]
When following the Custom CMSApp example, it isn't possible to use the `setExtra` method on the `authController` object within the authentication callback:

```js
  const { authLoading, canAccessMainView, notAllowedError } =
    useValidateAuthenticator({
      authController,
      authentication: async ({ user }) => {
        const idTokenResult = await user?.getIdTokenResult();

        // This method call triggers an error
        authController.setExtra({
          roles: {
            admin: !!idTokenResult?.claims?.admin,
            tutor: !!idTokenResult?.claims?.tutor,
          },
        });

        return (
          !!idTokenResult?.claims?.tutor ||
          !!idTokenResult?.claims?.admin ||
          false
        );
      },
      dataSource,
      storageSource,
    });
```

This triggers a depth exceeded error. I have traced this back to `useBuildNavigationContext.tsx` which has a `useCallback` with `authController` as one of the dependencies. I believe the change to the `authController` object from within the callback is causing the `useEffect` in that file to keep triggering.

Please let me know if I can give any further information, and I just want to say a massive thank you for your efforts - this library is a game changer for us!

**Comment by fgatti675** [comment]
Thanks @joestephens !
I'm checking this

**Comment by fgatti675** [comment]
If you wrap your function in `useCallback` it should work fine
```
    const myAuthenticator: Authenticator<FirebaseUser> = useCallback(async ({
                                                                    user,
                                                                    authController
                                                                }) => {
        const idTokenResult = await user?.getIdTokenResult();

        // This method call triggers an error
        authController.setExtra({
          roles: {
            admin: !!idTokenResult?.claims?.admin,
            tutor: !!idTokenResult?.claims?.tutor,
          },
        });

        return (
          !!idTokenResult?.claims?.tutor ||
          !!idTokenResult?.claims?.admin
        );
    }, []);
```
We will check how we can do to prevent this problem if useCallback is not used

**Comment by joestephens** [comment]
This works a treat. Thank you very much!

**Comment by fgatti675** [comment]
Welcome! 
This should be fixed in the latest versions without using `useCallback` anyway
