### ISSUE TITLE
React app showing blank screen after following quickstart guide (v1)

### ISSUE THREAD

**Issue by richardszegh** [Camberi/firecms#375]
I followed the quickstart (v1) guide to setup a React app, here's what I did:

1. create React app via TS template (yarn command copied from quickstart)
2. install dependencies (yarn command copied from quickstart)
3. copied the quickstart code for `App.tsx` (also copied in the Firebase project config from my Firebase project)
4. ran the app

I guess steps to reproduce are the same, just follow quickstart guide, enter Firebase config variables and run the app.

Tried to reproduce, issue happened multiple times, what solved is was to change the `@camberi/firecms` version from `1.0.2` to `1.0.3-pre.2` in `package.json` and then run `yarn` again. App was showing login screen after this.

**Comment by fgatti675** [comment]
Thank you @richardszegh 
We will release version 1.0.3 since it seems to fix the issue

**Comment by jfbourne** [comment]
still seeing the same issue here in 1.0.2. No V1.0.3 available.

**Comment by fgatti675** [comment]
Hi everyone, version 1.0.3 has been released and should fix the blank screen issue.Keep in mind you may need to add the dependency `@mui/x-date-pickers@^5.0.0-beta.1` if you didn't have it already
