### ISSUE TITLE
The fileName callback doesn't allow async functions

### ISSUE THREAD

**Issue by ciriousjoker** [Camberi/firecms#376]
- This is a follow up to #64

```ts
    storage: {
      ...

      // This will not work
      fileName: async (context) => await doSmth(),
    }
```

This is critical, because the file's arraybuffer is a Promise, so right now it's not possible to read the file's content before uploading (for example to calculate a proper hash).

(I'm on `2.0.0-alpha.29`)

**Comment by fgatti675** [comment]
Added async callbacks in `2.0.0-alpha.30` ;)
