### ISSUE TITLE
Can't use interfaces (only types) when defining a collection's data model

### ISSUE THREAD

**Issue by ciriousjoker** [Camberi/firecms#377]
#### Error message

> Type 'MyDoc' does not satisfy the constraint '{ [Key: string]: CMSType; }'.
  Index signature for type 'string' is missing in type 'MyDoc'

![image](https://user-images.githubusercontent.com/16866223/189470184-d243a93f-9188-4f5c-812c-9e877216bf35.png)

#### This doesn't work:

```ts
interface MyDoc {
  test: string;
}

buildCollection<MyDoc>({});
```

#### This works but requires using types:

```ts
type MyDoc = {
  test: string;
}

buildCollection<MyDoc>({});
```

#### This works but is ugly and prevents sharing the interfaces with the backend:

```ts
interface MyDoc  {
  test: string;
  [Key: string]: CMSType;
}

buildCollection<MyDoc>({});
```

#### This is a bit prettier, but only works for top level properties (nesting an array won't work because it expects `dataType` map for some reason:

```ts
interface MyDoc  {
  test: string;
}

type CMSWrapper<T> = T & {
  [Key: string]: CMSType;
};

buildCollection<CMSWrapper<MyDoc  >>({});
```

Is there a way to use interfaces as typings when defining a collection model?

**Comment by fgatti675** [comment]
Hi @ciriousjoker 
Can you check if this still happens in version `2.0.0-alpha.30` ?

**Comment by ciriousjoker** [comment]
Thanks, works perfectly!
