### ISSUE TITLE
How to unselect an item?

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#394]
Hi!

A question: We have in our document a field where the user can select a value from a list. Same as you have in your demo application "Category" for product
![grafik](https://user-images.githubusercontent.com/65586807/192722353-3578d59a-1038-4459-9fe2-c20df8b9943a.png)

our field is **not** a Must-Field, it is optional. Therefore the user can leave it empty.
The problem: If the user has assigned a value and later wants to remove it again, how can it be done? it seems that firecms makes a value required as soon once a value is assigned?

thanks for your feedback!

**Comment by fgatti675** [comment]
Hi Andre, we have an issue for the same request https://github.com/Camberi/firecms/issues/391
We can follow the discussion there :)
