### ISSUE TITLE
displayed my sensitive data in production

### ISSUE THREAD

**Issue by AchrafBn** [Camberi/firecms#399]
Hi,  
There is a log display my config firebase in production , I'm using latest version. 1.0.2

<img width="1437" alt="Screenshot 2022-10-10 at 11 58 57" src="https://user-images.githubusercontent.com/11798130/194851427-480dda72-3307-4a95-98c7-ee6586e0f25d.png">

**Comment by fgatti675** [comment]
Hi @AchrafBn, that log message is not there anymore in version 2.0 in case you want to upgrade.
In any case, that data is not sensitive! It is bundled in your frontend code and anyone using your app can access it
