### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by altechzilla** [Camberi/firecms#4]
```
./node_modules/typeface-roboto/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@camberi/firecms/dist/index.modern.js
```

**Comment by fgatti675** [comment]
We actually haven't tested the library with next.js so can't guarantee it's going to work now.
But for now I have removed the CSS import in version 0.11.1
Maybe check it out and let me know if it works!

**Comment by altechzilla** [comment]
That worked! The error is gone.
