### ISSUE TITLE
Filter by Boolean equal to false

### ISSUE THREAD

**Issue by djanogly** [Camberi/firecms#40]
I am looking to filter by a Boolean value, but when the filter is unselected, it includes 'true' values as well as 'false' values.

I would like to be able to filter so as to see only entries whose bool value is false. 

I hope that is clear, let me know if not!

Thanks,
Jack

**Comment by fgatti675** [comment]
Hi Jack! A rework of the filters is already planned :)

**Comment by fgatti675** [comment]
Fixed in version 0.43.0
