### ISSUE TITLE
Uncaught Error: Trying to resolve a property builder without specifying the entity path

### ISSUE THREAD

**Issue by irmakcan** [Camberi/firecms#410]
Hi,

I have these two collections.

```js
const productsCollection = buildCollection<Product>({
  name: "Products",
  singularName: "Product",
  path: "products",
  properties: {
    name: {
      name: "Name",
      validation: { required: true },
      dataType: "string"
    },
    related_songs: {
      dataType: "array",
      name: "Related products",
      description: "Reference to self",
      of: {
        dataType: "reference",
        path: "songs"
      }
    },
  },
  ...
});

const songsCollection = buildCollection<Song>({
  path: 'songs',
  name: 'Songs',
  singularName: 'Song',
  properties: {
    title: {
      name: 'Title',
      dataType: 'string',
      validation: {
        required: true,
      },
    },
    product_ref: {
      name: 'Parent Product',
      dataType: 'reference',
      path: 'products',
      validation: {
        required: true,
      },
    },
  },
  ...
});
```

When I try to set a product in songs collection I get this error on the UI:

![error](https://user-images.githubusercontent.com/733117/197632959-80d5023e-7e6a-4e49-b4f8-349be5891b44.png)

Console: 
```
Uncaught Error: Trying to resolve a property builder without specifying the entity path
    at Me (resolutions.ts:108:1)
    at Lc (property_utils.tsx:17:1)
    at references.ts:15:1
    at Array.filter (<anonymous>)
    at Ri (references.ts:9:1)
    at ReferenceFieldBinding.tsx:162:1
    at wd (ReferenceFieldBinding.tsx:279:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
```

It actually sets the product reference in the db but I can't edit or see in the UI. Is this my mistake? How can I resolve this issue?
FireCMS: `2.0.0-alpha.41`
Thank you.

**Comment by fgatti675** [comment]
Hi, I have tested this exact code with the latest version and could find no problems!
I am closing this for now.
If you still have issues, feel free to reopen and maybe provide more details about your implementation

**Comment by espAvalon** [comment]
Having same issue when i reference collection that have field with Property builder
In entity view it displays like it should , showing error when i open sideview with same error in console

**Comment by espAvalon** [comment]
When I use property builder for picture collection to disable image field if type is not chosen. It shows error
`const pictureCollection = buildCollection<PictureCollection>({
  name: 'Picture',
  singularName: 'Picture',
  path: COLLECTIONS.images,
  alias: 'images',
  properties: {
    type: {
      name: 'Type',
      dataType: 'string',
      enumValues: ImageType,
    },
    image: ({ values }) => ({
      dataType: 'string',
      name: 'Image',
      storage: {
        storagePath: 'images',
        acceptedFiles: ['image/*'],
        fileName: '{rand}{file}',
        metadata: {
          cacheControl: 'max-age=1000000',
        },
      },
      disabled: !values.type,
    }),
  },
});

const exampleCollection = buildCollection<PosterAndThumb>({
  name: 'Pictures',
  singularName: 'Picture',
  path: 'example',
  properties: {
    poster: {
      name: 'Poster',
      dataType: 'reference',
      path: COLLECTIONS.images,
      previewProperties: ['image'],
      forceFilter: {
        type: ['==', ImageType.poster.id],
      },
    },
    thumbnail: {
      name: 'Preview',
      dataType: 'reference',
      path: COLLECTIONS.images,
      previewProperties: ['image'],
      hideFromCollection: true,
      forceFilter: {
        type: ['==', ImageType.thumbnail.id],
      },
    },
  },
});`

Having this in side view and error in console

![Screenshot](https://user-images.githubusercontent.com/25417976/203072762-bdd39030-0b9f-401f-9846-a345851ec73a.png)

index.e9f4b6c2.js:221398 Error: Trying to resolve a property builder without specifying the entity path

If I leave property builder and simply remove disabled issue stays. It goes away only if I remove property builder

version used: "@camberi/firecms": "^2.0.0-alpha.45"

**Comment by fgatti675** [comment]
Found the issue, getting fixed in the next release!

**Comment by fgatti675** [comment]
This bug has been fixed in the latest release :)
