### ISSUE TITLE
Two filters in one list

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#416]
hi @fgatti675 
during daily work we often have to apply 2 or even 3 filters in a list of products. Otherwise we cant narrow the documents down to the set we like to work with.
Example: Lets say the product collection has 5000 products.
Now I want to select all products with color="blue" and type="t-shirt".
This is currently not possible, as soon I apply 2nd filter, the first is lost.
Is there a way to do it? Or is it solved in 2.0? (we just now started migration).
thanks for your feedback, and have a great day!
Andre

**Comment by Andre3424** [comment]
hi @fgatti675, as I understand it is a restriction by firestore, however, is there no workaround? How are other working having the use case above? Example above: I dont want products only with color blue or type only t-shirt. I want blue t-shirts. And as editors work in 90% of cases: First filter t-shirt, then maybe sort by create-date, then filter by color=blue.

if you could give a short feedback would be great, thanks!

**Comment by fgatti675** [comment]
Hi @Andre3424 
I understand the pain point. Unfortunately we are very limited by what Firestore provides in terms of filtering and sorting.
In any case, it would be possible to use an external indexing system like Algolia or Elasticsearch to index data, and use it as the data provider when filters and search are applied. We would need to do a custom development for that.
Feel free to reach to us if this seems interesting to you :)
The indexes are still there in v2, they are called `filterCombinations`

**Comment by Andre3424** [comment]
@fgatti675 thanks for your feedback! We will integrate Algolia in next 2-3 weeks and check it. We will be glad to contact you.
What I just wonder: When we retrieve recrods from firestore, are they not kept in an array in memory and we could apply sorting or additional filtering in that array?

**Comment by fgatti675** [comment]
It is tempting to just load the whole collection and do the filtering client side, but that would not work for larger collections.
Some users have collections with 100k records!
It would become irresponsive quickly.
So the integration we have right now with algolia allows users to do text search, but not select multiple filters.
Text search might be good enough for you though!

**Comment by Andre3424** [comment]
@fgatti675 Yes, this is right, we dont want 100k records locally :-)
Search is an option, but coming from traditional SQL databases which also have thousands of records, we are still looking for a more comfortable way.
I understand we cannot combine (several) filters and/or (several) sortings. However, assuming we would query data again, this would work. What I mean:

1: user sets filter type=camera and then all cameras are shown
2: now user sorts by name. 
**The intention of the user**: Sort cameras sorted  by name.
**Ideal technical implentation:**FireCMS simply sends now a **new** request to firestore to retrieve cameras sorted by name.

3: Now user filters by brand "Canon"
**The intention of the user**: Canon cameras sorted by name.
**Ideal technical implentation:**FireCMS simply sends now a **new** request to firestore to retrieve canon cameras sorted by name.

4: User wants to clear filters. There is a button to clear filters
