### ISSUE TITLE
Mobile improvment and display file format data.

### ISSUE THREAD

**Issue by KULTI1995** [Camberi/firecms#418]
please change the display form of the sidebar so that it does not cover 1-3 of the screen on the mobiles. Basically I will say yes, a brilliant design. Keep it up.
I propose to add a view in addition to the image, add a view of all the others with the format in the form of gadge, and an abbreviation of the name. :) So that all other formats would be displayed in a cool way. And by no means to me - Adding a display of the number of letters in files, or the number of words.

**Comment by fgatti675** [comment]
Thank you @KULTI1995 
We are aware of the layout issues on mobile and will work on it!
But I am afraid I didn't understand the display file format data

**Comment by fgatti675** [comment]
Mobile improvements in version `2.0.0-alpha.45`
