### ISSUE TITLE
buildCollection->views button doesn't work as expected

### ISSUE THREAD

**Issue by nicosaurus91** [Camberi/firecms#429]
<img width="654" alt="Screenshot 2022-11-10 at 11 19 13" src="https://user-images.githubusercontent.com/117906241/201065205-f127ede4-caa6-459a-a4b7-e3772a7554e0.png">
<img width="574" alt="Screenshot 2022-11-10 at 11 19 42" src="https://user-images.githubusercontent.com/117906241/201065218-1a7871a0-fa8b-4413-a758-202f02aec46b.png">
<img width="574" alt="Screenshot 2022-11-10 at 11 19 42" src="https://user-images.githubusercontent.com/117906241/201067716-3dc9017e-bfcb-4c65-851b-0381655f7ca6.png">

Hi!

**F**irstly, thank you for your excellent work! I was on sanity for a while, but because of technical limitations, I move my app to Firebase. I needed a premade CMS and firecm was the answer!

Regarding my problem:
I want to have two custom view into my collection. So I did what you can see in attachment. (I assume it's the correct way to do it.).

Unfortunately, it's impossible to have 'player' tab displayed. When I click on the button of it, it goes to the last tab, and it selects "answers". I can see briefly 'player' tab before it goes back to 'answers'.

I tried different path, but's it's always the same :(

Is something wrong?

**UPDATE**

<img width="612" alt="Screenshot 2022-11-10 at 11 38 53" src="https://user-images.githubusercontent.com/117906241/201069583-617a5526-7894-40c4-8488-bce5014e8b43.png">

It seems to works when I left one of the path empty.. but it doesn't when both path are filled.. Weird, maybe the router?

Thank you for your answer and have a good day!

Nicolas

**Comment by fgatti675** [comment]
This is a bug, it will be fixed in the next release :)

**Comment by nicosaurus91** [comment]
Thank you!

**Comment by fgatti675** [comment]
Should be fixed in `2.0.0-alpha.45` :)
