### ISSUE TITLE
Field values depending on another field

### ISSUE THREAD

**Issue by faizaand** [Camberi/firecms#43]
I have a custom field that shows a dropdown of choices, but it accepts a "year" prop that filters the choices by year. I want to make it such that if the user selects a certain year (defined in the schema), that it passes this year to the custom field in its `fieldProps`. Is that possible in the current software?

**Comment by fgatti675** [comment]
Hi @faizaand, in version 0.24.0 you now have a context object passed in the CMSFieldProps, there you have access to the other values of the form. Let me know if that works for you!
