### ISSUE TITLE
Unable to copy a schema

### ISSUE THREAD

**Issue by warrenrhodes** [Camberi/firecms#431]
After migration to version 2.0.0, copying the schema rather modifies the previous schema because it also copies its identifier instead of generating another one, so the system thinks that it is an edition.
<img width="1347" alt="Screenshot 2022-11-10 at 16 05 11" src="https://user-images.githubusercontent.com/46690709/201131842-15df6585-1ec3-4f7a-9e6a-f7adf6251eb8.png">

**Comment by fgatti675** [comment]
What is your config in the `customId` prop?

**Comment by fgatti675** [comment]
Should be fixed in `2.0.0-alpha.45` :)
