### ISSUE TITLE
Version 2.0 the copy of a schema modifies the existing one instead of duplicating it

### ISSUE THREAD

**Issue by warrenrhodes** [Camberi/firecms#432]
This is due to the fact that the CMS also duplicates the id instead of generating another one 
<img width="1347" alt="Screenshot 2022-11-10 at 16 05 11" src="https://user-images.githubusercontent.com/46690709/201463808-da9a4bd1-d158-4336-860e-34ed388ede67.png">

**Comment by fgatti675** [comment]
Fixed in version `2.0.0-alpha.45`
