### ISSUE TITLE
FireCMS V2 - Login screen with endless busy symbol

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#433]
@fgatti675 hi Francesco
we migrated now our system to V2 and tested it. Looks almost everything good, just one problem we have: On the login screen the busy-symbol is shown forever and login does not appear. The login page only appears if we add allow read in the fules for documents in firestore:
![grafik](https://user-images.githubusercontent.com/65586807/201483160-c33b23f3-dff5-4a75-bfd0-75a0358af37f.png)

In Firecms V1 this is not needed. Why is it need here?
thanks,
best regards
Andre

**Comment by fgatti675** [comment]
Improved error handling in collection build process will be released in next version :)
