### ISSUE TITLE
Suggestion: Initial Sort

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#44]
Hi there!

Great ongoing work on this! I was thinking that it will be super helpful to have a way to setting the field we wish to sort by initially. For example, we could set the initial sort based on updated date, so we know what docs were last edited.

I apologize if this is supported already. I couldn't find it in the readme doc.

**Comment by fgatti675** [comment]
Added `initialSort` in version 0.25.0 :)
