### ISSUE TITLE
Broken custom colors for number dataType select

### ISSUE THREAD

**Issue by Ziiiiiiiiit** [Camberi/firecms#445]
If you configure a select collection property with a number type, and define custom colors for its enumTypes the custom colors will never be used. (It will default to some standard array instead).

This is because of a bug in ColorChip.tsx, where enumKey.toString() is sent to the getColorScheme utils function rather than just enumKey. This makes the getColorScheme function unable to retrieve the proper configuration unless the key was already a string.

Change row 40 from:
const colorScheme = getColorScheme(enumValuesConfig, enumKey.toString());
to:
const colorScheme = getColorScheme(enumValuesConfig, enumKey);
to solve.

**Comment by fgatti675** [comment]
Should be fixed in the latest release :)
