### ISSUE TITLE
Where do get newest version?

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#446]
@fgatti675 Hi Francesco

We wanted tou install the newest version to have the fix mentioned in https://github.com/Camberi/firecms/issues/441.
However, when we use yarn upgrade @camberi/firecms it installs version 1.0.2.

Where can we find the newest version of V2?

thanks and have a good day
André

**Comment by Andre3424** [comment]
@fgatti675 update: We found it, however it was somewhat confusing that the changelog is not updated.
And should the command above now install the newest version?

**Comment by fgatti675** [comment]
We are starting a new changelog for FireCMS v2 :)
https://firecms.co/docs/changelog

**Comment by Andre3424** [comment]
great!
