### ISSUE TITLE
Edit related prodcuts no more work

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#447]
hi @fgatti675 !
Hope you are well, I wish you all the best in 2023!
We have just discovered, that in the newest fireCMS the releated-function no more works, also in your demo where you use it as "edit related prodcuts". See error and video from your demo site enclosed.
<img width="483" alt="Screenshot 2023-01-02 at 14 27 36" src="https://user-images.githubusercontent.com/65586807/210232190-20fba534-75a7-4acf-8120-ccb827f10380.png">
![grafik](https://user-images.githubusercontent.com/65586807/210232284-367047a2-b449-4e7b-9283-7010961cf715.png)

could you take a look? Thanks!

**Comment by fgatti675** [comment]
Hi @Andre3424 This was just fixed in the latest release, thanks!

**Comment by Andre3424** [comment]
@fgatti675 thanks for this fast fix!
