### ISSUE TITLE
all additionalFields in collection Views disappeared

### ISSUE THREAD

**Issue by Andre3424** [Camberi/firecms#449]
hi @fgatti675 
We installed the newest release according https://github.com/Camberi/firecms/issues/447
however, with this release all custom fields in collection views have gone and are no more visible. We reverted therefore back to the previous version.
Also in your demo it seems no more to work 
https://github.com/Camberi/firecms/blob/a12bad029d595c36ecd3111b8936fb987b31427a/example/src/SampleApp/collections/products_collection.tsx#L124

Could you please check this?
thanks!

**Comment by fgatti675** [comment]
Sorry! Should be fixed in `2.0.0-alpha.56`

**Comment by Andre3424** [comment]
@fgatti675 thanks for the fast fix!
A question: we somehow cannot see latest releases in changelog in offical docs, are there somewhere listed? It would be good when we can see per release what changed. thanks

**Comment by fgatti675** [comment]
Hi @Andre3424 
The changes are not currently listed anywhere.
We have been iterating very fast in the alpha versions of FireCMS 2.0.0.
We will be hitting beta soon and get back to the usual changelog
