### ISSUE TITLE
Changing the row size on collection with array of document references crashes the app

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#45]
Hi!

I have a collection with a field of array references (firebase doc ref). Each reference has another field called title. In the summary view, when the row size is the default M, it works fine. But when I change the row size to anything bigger than M, it shows an error on the array reference field and after a while shows this error:
TypeError: Cannot read property 'title' of undefined

The error occurs in src/preview/components/ReferencePreview.tsx:181

It is fine if I change the row size to anything smaller than M. I think it is because it doesn't load the additional entries when the row is bigger.

**Comment by faizanabidnaqvi** [comment]
I am not sure if this a mistake I was making or not but after updating to the latest version, this issue doesn't happen.

**Comment by fgatti675** [comment]
Yes yes, I did a change in reference to this in v 0.24.0, thanks!
