### ISSUE TITLE
Is there any way to enable what-you-see-is-what-you-get mode for Markdown editor

### ISSUE THREAD

**Issue by fe7ng654123** [Camberi/firecms#451]
I would like to edit markdown text in WYSIWYG mode.

is there any way I can make it happen, or import 3rd party React text editor?

Thanks!

**Comment by fgatti675** [comment]
Hi @fe7ng654123 
Could you make it work?
If the included markdown editor does not work for you, you can always build a custom field to replace it:
https://firecms.co/docs/properties/custom_fields

**Comment by fe7ng654123** [comment]
managed to make it with Toast UI editor and custom field. Thanks a lot
