### ISSUE TITLE
React 18 --> @mui/styles [FireCMS v1.0.3]

### ISSUE THREAD

**Issue by DevGrill** [Camberi/firecms#454]
Hello,

When installing `"@camberi/firecms": "1.0.3" ` I get the following error:
```node
npm ERR! peer react@"^17.0.0" from @mui/styles@5.11.2
npm ERR! node_modules/@mui/styles
npm ERR!   @mui/styles@"5.11.2" from the root project
npm ERR!   peer @mui/styles@"^5.9.0" from @camberi/firecms@1.0.3
npm ERR!   node_modules/@camberi/firecms
npm ERR!     @camberi/firecms@"1.0.3" from the root project
```

When visiting the [Documentation](https://mui.com/system/styles/basics/) from `@mui/styles` it tells me that it doesn't support React18, which is getting required by FireCMS:

```node
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"18.1.0" from the root project
npm ERR!   peer react@"^18.1.0" from @camberi/firecms@1.0.3
npm ERR!   node_modules/@camberi/firecms
npm ERR!     @camberi/firecms@"1.0.3" from the root project
```

Is there a fix for that besides using Yarn or flags like `--legacy-peer-deps` or `--force`?

Thanks for the help in advance.

**Comment by huynhit24** [comment]
npm i --force

**Comment by DevGrill** [comment]
> 

Without using `npm --legacy-peer-deps` or `npm --force`

Like written in the issue.

**Comment by DevGrill** [comment]
Fixed with npmrc
