### ISSUE TITLE
Showing subset of the columns in the list view

### ISSUE THREAD

**Issue by andrashee** [Camberi/firecms#457]
Hi @fgatti675, hope you are doing well.

We are still very happy with the tool and making great progress in setting it up in our context.

One question I have: how can we limit the tabular overview to only show a subset of the columns, but when you click on edit you can see all attributes?
That would help us a lot to keep a good overview.

Any ideas how to approach this? Many thanks!

**Comment by fgatti675** [comment]
Hi @andrashee 
You can use the `propertiesOrder` prop to select the properties and additional fields displayed in the table :)

**Comment by andrashee** [comment]
Thanks a lot! Works like a charm
