### ISSUE TITLE
App crashes after deleting an item

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#46]
Hi again!

In the latest version, that is 0.23.0, if I press the three dots to access the copy/delete menu, it opens up the doc edit popup at the same time as the menu shows up. Now if I press delete, the delete confirmation shows up and the address bar changes to the host/collection/[doc id]. When I press Ok on delete, the app crashes with a type error. 

It seems like it is because the address bar is still pointing to the doc that I deleted. 

Also, I like the new copy feature! I was going to mention that as a suggestion.

**Comment by faizanabidnaqvi** [comment]
Fixed!

**Comment by fgatti675** [comment]
Great thanks!
