### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by borsemayur2** [Camberi/firecms#464]
Getting mentioned error for `import _objectWithoutPropertiesLoose from "@babel/runtime/helpers/esm/objectWithoutPropertiesLoose";`

Working fine with Vite React app but getting this error with NextJS 13.1.2.

![image](https://user-images.githubusercontent.com/47341981/216107157-706d2a82-30cf-4ba3-8364-919fdaf9c36f.png)

**Comment by borsemayur2** [comment]
Fixed after using `dynamic import` with `ssr: false`

**Comment by fgatti675** [comment]
Hi @borsemayur2 
We have not really tested FireCMS with next.js since it's a frontend focused app, but `ssr: false` should work.
What is your use case?

**Comment by borsemayur2** [comment]
`ssr: false` did work. I'm integrating firecms for blog creation with the existing nextjs app hosted on firebase.
Thanks
