### ISSUE TITLE
setSelectedEntities on useReferenceDialog

### ISSUE THREAD

**Issue by juanandres86** [Camberi/firecms#468]
![Captura desde 2023-01-31 09-31-09](https://user-images.githubusercontent.com/109976138/217578139-c76f1247-3e5e-4e70-b51d-ee71fad33ee1.png)

In the latest version 2.0.0-beta.2 inside useReferenceDialog it does not set setSelectedEntities, after setting it if I read selectedEntities it is empty

**Comment by fgatti675** [comment]
Hi @juanandres86 
I suspect this was related to a different issue that was fixed in the latest versions.
I am closing it for now, but feel to reopen if the problem persists
