### ISSUE TITLE
Clicking the checkbox in the id field opens up the document popup

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#47]
I like the new checkbox feature, together with allowing multiple deletes. But it is inconvenient right now because whenever I check an item, it also opens up the item details popup which I then have to close to proceed with checking more items.

This is similar to the issue where clicking the 'three dots' to open the copy/delete menu also opens the item details popup.

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi, which browser and OS are you using?
It doesn't seem to happen in Chrome on MacOS

**Comment by faizanabidnaqvi** [comment]
Hi @fgatti675 

Thanks for getting back! I am using Chrome on MacOS too!

Here are videos for the checkbox issue and the 3 dots issue (they are similar)

https://user-images.githubusercontent.com/5749036/105866577-6bca2180-5ff4-11eb-9935-5891952de7b6.mov


https://user-images.githubusercontent.com/5749036/105866637-797fa700-5ff4-11eb-8ee0-5c10496d2278.mov

**Comment by faizanabidnaqvi** [comment]
It's fixed in 0.24.0! :)

**Comment by fgatti675** [comment]
Great thanks! :)
