### ISSUE TITLE
Error when using a number as key for a map

### ISSUE THREAD

**Issue by mxswat** [Camberi/firecms#475]
The UI does not allow you to create or save the document when using the following code. 
And it shows an error with just a number, as you can see in the screenshot below

I'm using `"firecms": "^2.0.0-beta.2",`

```tsx
import { buildCollection, buildProperty, EntityReference } from "firecms";

export type GearSet = {
  bonuses: {
    [count: number]: {
      primitiveStatId?: EntityReference;
      statValue?: number | null;
      talentId?: string;
    }[];
  };
  id: string;
};

const bonusProperty = (name: string) =>
  buildProperty({
    name: name,
    validation: { required: false },
    dataType: "array",
    oneOf: {
      properties: {
        gearTalent: {
          dataType: "reference",
          path: "thedivision2/schema/geartalents",
          name: "Gear Talent",
          validation: { required: true },
        },
        stat: {
          dataType: "map",
          properties: {
            primitiveStat: {
              name: "Primitive Stat",
              path: "thedivision2/schema/primitivestats",
              dataType: "reference",
              validation: { required: true },
            },
            value: {
              name: "Stat value",
              dataType: "number",
              validation: { required: true },
            },
          },
        },
      },
    },
  });

export const GearSetCollection = buildCollection<GearSet>({
  name: "Gear Brands & Gear Sets",
  group: "The Division 2",
  path: "thedivision2/schema/gearsets",
  customId: true,
  icon: "LocalLibrary",
  properties: {
    id: {
      name: "Id",
      validation: { required: true },
      dataType: "string",
    },
    bonuses: {
      name: "Bonuses",
      dataType: "map",
      spreadChildren: true,
      properties: {
        "1": bonusProperty("Set Bonus 1"),
      },
    },
  },
});
```

![image](https://user-images.githubusercontent.com/17874432/223769338-b12b048b-33bb-4f6d-953f-69fb790ab41e.png)

My workaround was to replace this line
```tsx
 "1": bonusProperty("Set Bonus 1"),
````

With this line, and forcing the key to be a string
```tdx
 "#1": bonusProperty("Set Bonus 1"),
```

**Comment by fgatti675** [comment]
Hi @mxswat 
Thanks for the catch, unfortunately this bug is harder to fix than what we expected.
We use formik internally for managing data, where fields are accessed using paths like `address.street`, for objects, or `tags.1` or `tags.7`  for arrays.
When you add a property that has numbers as the key, the system gets confused. We would need a big investigation a refactor to fix this case.
At this moment I would advise using strings as keys (which don't represent numbers)

**Comment by fgatti675** [comment]
The related formik issue: https://github.com/jaredpalmer/formik/issues/1365.
I am closing this for now since we can't fix it directly :(

**Comment by mxswat** [comment]
Well, thank you for investigating! I'll figure out a way around it.
