### ISSUE TITLE
Allow dropping of files to upload directly in editable tables

### ISSUE THREAD

**Issue by fgatti675** [Camberi/firecms#48]

**Comment by anshsrtv** [comment]
Is this issue related to the mass upload of documents to collections with files of CSV/JSON format?

**Comment by fgatti675** [comment]
Hi @anshsrtv 
No it isn't! This one related to be able to drag and drop files directly in the collection view (now you can only upload files like that in the form views).
We don't currently have a ticket for mass uploading or importing documents, but feel free to create one :)

**Comment by anshsrtv** [comment]
Hi @fgatti675! I have created #97 and also look forward to solving it. It will be great if you could help me find the right approach for it since I'm new to the repository and codebase.

**Comment by fgatti675** [comment]
Added in version 1.0.0-beta5
