### ISSUE TITLE
Being able to have no icons displayed 

### ISSUE THREAD

**Issue by SeeringPhil** [Camberi/firecms#480]
The documentation states that : _You **can** now assign icons to collections and custom views_

When I read this I understand that I should be able to also **NOT** assign icons and that it would indeed not display an Icon. 
However, right now, when you don't assign an icon to a collection, there is one that is displayed randomly in the navigation bar. 

I feel like there should be a way to have no icons displayed if we don't want any. 

Maybe if no collections have icons, it could revert back to the way v1 was, and have no icons and only show the name of the collections when hovering?

**Comment by fgatti675** [comment]
Hi Phil, this is not something planned for the near future. The icons are needed for the collapsed navigation bar.
If you want something similar to V1, you can assign the V1 icon to all your collections
