### ISSUE TITLE
Uncaught TypeError: flexsearch__WEBPACK_IMPORTED_MODULE_14___ default(...) is not a constructor

### ISSUE THREAD

**Issue by jellibeans-ted** [Camberi/firecms#488]
Uncaught TypeError: flexsearch__WEBPACK_IMPORTED_MODULE_14___ default(...) is not a constructor at FireCMSHomePage.tsx:22.

![image](https://user-images.githubusercontent.com/126437083/229766509-7491837e-3ade-4375-bf93-48d4e23b3d4b.png)
![image](https://user-images.githubusercontent.com/126437083/229766680-9ce808b9-7fbb-4415-857c-6ac1a418d7b9.png)
 
 the default component of flexsearch can't be Index.
 I hope to make sure if it is my fault or module bug?

**Comment by fgatti675** [comment]
That is a new dependency, did you run `yarn` ?

**Comment by jellibeans-ted** [comment]
Not, I didn't used `yarn`. just used `npm`

**Comment by agramian** [comment]
What was the resolution to this issue?

I am getting the same error when trying the quick start instructions with a new create react app regardless of using `yarn` or `npm`.

Is only vite supported now? I was using v1 of firecms with an ejected create react app project and have only now run into issues after attempting to migrate to v2 of firecms.

Here are steps to reproduce with `yarn` and a new create react app project:
1. `yarn create react-app my-cms --template typescript`
1. `cd my-cms`
1. `yarn add firecms@^2.0.0 firebase@^9 @mui/material@^5 @mui/icons-material@^5 @mui/lab@latest @mui/x-date-pickers@^5.0.0-beta.1 @emotion/react @emotion/styled react-router@^6 react-router-dom@^6`
1. Choose 2.0.0-beta.5 when prompted by yarn.
1. Replace the contents of `src/App.tsx` with the code from the [Quickstart](https://firecms.co/docs/quickstart) (including values for the firebase config).
1. Run `yarn start`.

**Comment by fgatti675** [comment]
Thanks for the explanation, the new library was causing errors with webpack.
We have fixed the code and deployed a pre version: `2.0.0-beta.6-pre.2` :)
