### ISSUE TITLE
Single Content Type

### ISSUE THREAD

**Issue by shelooks16** [Camberi/firecms#49]
Hey,

I was wondering whether single content type can be somehow plugged in? 

What I mean is that suppose there is a collection "pages" where each doc id is page name and each document has different structure. 
For example /pages/about, /pages/home. 
`about` and `home` are document ids. Each document has its own unique structure. 

Firecms navigation is an array of collections and every collection must follow defined schema (Entity). 
The easiset workaround I can think of right now is to build multiple views for a single collection and apply filter on a document field that uniquely identifies that document in the collection:

```
const navigation: EntityCollectionView[] = [
  buildCollection({
    group: 'Pages',
    name: 'Home',
    relativePath: 'pages',
    schema: homePageSchema,
    initialFilter: {
      page: ['==', 'home']
    }
  }),
  buildCollection({
    group: 'Pages',
    name: 'About',
    relativePath: 'pages',
    schema: aboutPageSchema,
    initialFilter: {
      page: ['==', 'about']
    },
  })
];
```

Although each document needs an additional field in order to be uniquely filtered out, theoretically it should work. 
However.... This does not work in reality. Firecms generates views based on path in firestore. 
With above workaround, 'Single-Types' will share the same view: `/c/pages` that will display only first matched EntityCollectionView. Maybe an additional prop to specify custom route will do the trick?

An ideal API would look something like:
```
buildSingleType({
  group: 'Pages',
  name: 'Home',
  relativePath: 'pages/home',
  schema: homePageSchema,
})
```

Let me know what do you think

**Comment by fgatti675** [comment]
Hi @shelooks16 
That's a very interesting use case!
I have given this a bit of a thought. We are currently working on exposing internal APIs, in order to give developers more freedom. 
One of the functionalities we would like to provide is the possibility to open the side dialog for editing entities. So I am thinking, you could create a custom view using the `additionalViews` prop. You could build your own list of pages, with buttons that, when clicked, they open the selected entity with the selected schema.
How does that sound?

**Comment by shelooks16** [comment]
Hi @fgatti675 

I was actually thinking about somehow using `additionalViews` too but didn't come up with anything.

Thanks for sharing! Internal APIs feature sounds really cool :)

Not sure whether I got it right:

> You could build your own list of pages, with buttons that, when clicked, they open the selected entity with the selected schema.

Having that new feature of side dialog for editing entities, I would click on a button that opens a single document for edit in the side-menu? Just like when 'Add New' clicked but for editing?

**Comment by fgatti675** [comment]
Yes exactly! 
So you would be able to select the path to your entity, the schema and some other parameters, using a custom hook.
We are working now on decoupling the current implementation from collection views, where those parameters get extracted from.
I will keep you updated :)

**Comment by shelooks16** [comment]
@fgatti675 that sounds amazing :) 
Thanks a lot for keeping me updated. Looking forward for any updates!

Can I take a moment for one more thing? Could you expose an API to disable the save-as-you-write feature when editing in a table row? This becomes super inefficient when there is a firestore trigger that listens for document updates. A button to save new changes would be very much appreciated :)

Just want to leave my word that FireCMS is just a gem which stands out among other solutions for firestore. It's not just a UI to view tabular data (like pushtable), the lib has some real vibes. It is extensible, customizable, typescript supported, free, and the most important - developer friendly.

**Comment by fgatti675** [comment]
Thanks a lot for your very nice words @shelooks16 :)
We have big plans for FireCMS! And both developers and the end users are the main focus.

I'll look into disabling save-as-you go, but right now is tightly coupled with the Table component. Also from the UX perspective feels tricky, but maybe we can try saving onBlur only. For now, I'd suggest disable inline editing!

Regarding the original question, there is a new hook exposed in the CMS API in version 0.25.0: `useSideEntityController`. You can use it to open specific entities with specific schemas (or the registered one, if not specified). It has been added in the main README.md

Also, this is not documented but there are some additional components that have been exported, in an experimental phase:
- `EntityCollectionTable`: binds an EntityCollection to a view (it is the component used in the main view including a table of entities and in the subcollection views)
- `CollectionTable`: Lower level implementation of a table that gets bound to a collection and a schema but offers a lot more customization. You can customize the actions per row as well.

I think that with these components and a little bit of extra work, you should be able to build a collection view and assign a custom schema to each entry. But consider these components are bound to change in the future!

Let me know how that works for you and if I can help you in any way!

**Comment by shelooks16** [comment]
Yeah, onBlur sounds great.
Let me try out new version. I will post an update here.

**Comment by shelooks16** [comment]
@fgatti675 

I checked out new features. They look very promising but all of them have one common problem. I created the repo to reproduce if needed and also deployed to see exactly what is wrong.

repo: https://github.com/shelooks16/firecms-playground
live: https://lucid-leakey-753695.netlify.app/

- **useSideEntityController**: all is good until the sidebar is closed. When sidebar opens, it changes the URL to match document path in firestore: `/c/collectionId/docId`. Once the sidebar is closed, the app throws an error if the collection of the opened document is not part of the main navigation passed to `<CMSApp />`. Since route for the collection was not generated, the app throws `Couldn't find the corresponding collection view for the path: ...`
- **EntityCollectionTable**: basically the same as for `useSideEntityController`. When clicking on ADD or EDIT, it changes the URL to match path in firestore, and since route for that path was not generated, it throws exactly the same error.

Please take a look at the live version. 

Firestore structure is:
```
.
├── rooms
│   ├── room1
│   └── room2
└── pages
    ├── page1
    └── page2
```
room1, room2, page1, page2 are document ids. All documents have the same structure: `{ title: string }`. 
`rooms` collection is part of the main navigation while `pages` not. For that reason, only `pages` collection works.

**Comment by fgatti675** [comment]
Hi @shelooks16 :)
First of all, thanks a lot for your very detailed error report and test project!
You were right, EntityCollectionTable was tightly coupled with the overall navigation.
In version 0.25.1 I have added an internal schema registry that allows to fetch the side panels configuration from different places:
- The main navigation as defined until now
- The current context (such as a manually defined `EntityCollectionTable`)
- A `schemaResolver` property you can set in the `CMSApp` level, to override specific schemas.
- Custom schema configurations set explicitly using `useSideEntityController`

I think in your case, you will probably want to set the `schemaResolver` so you can override schemas all through the app.
I have checked your project and I think everything looks good with the latest version. 
Let me know how it works out for you!

**Comment by shelooks16** [comment]
Hey, @fgatti675

The update with custom resolvers looks awesome! 
As far as I understood, custom `schemaResolver` can be used on `<CMSApp />` to manage all schema Entities from one place. I think passing schema explicitly to `useSideEntityController` is more intuitive. Anyways, now there is more space for customization :)

Thanks! I think the issue can be closed now. If you need any feedback or anything let me kno!.

**Comment by fgatti675** [comment]
Hi @shelooks16 

Yeah! I felt the same about being more intuitive having it in `useSideEntityController`, so I also left it there, you can override the schema locally, just as you did before :)
I tested your project and everything seems to be working fine.

While going through all the cases were `useSideEntityController` is used internally, I realised that we also use it for references (you can click on a reference and open the side dialog related to it anywhere within the app). We needed a way to override schemas app wide, so that's why I also added `schemaResolver`.

Looking forward to hear how things worked out for you!

**Comment by shelooks16** [comment]
Everything works smoothly. I will stick with schema passed directly to `useSideEntityController`. At the moment, there is no need for me to use custom `schemaResolver`. 

Single content type was succesfully achieved haha :) And it's even better than that since independent documents can be grouped together in an AdditionalView. That was super useful update!

**Comment by fgatti675** [comment]
Great to hear!
Please let me know how things go for you from now on, your feedback was really valuable! :)
