### ISSUE TITLE
Permissions cannot be used to hide a collection from the user's navigation but the code says it should

### ISSUE THREAD

**Issue by SeeringPhil** [Camberi/firecms#496]
The comments in permissions.ts lead to believe that the _read_ attribute on the permissions interface will allow to hide a collection from the user's navigation. 
https://github.com/Camberi/firecms/blob/b893b940c48ecd1640fb1a66e1fe001df91688ad/lib/src/types/permissions.ts#L11-L16

However, setting this to false does not hide anything from the navigation.

**Comment by fgatti675** [comment]
That was a bug, should be fixed in `2.0.0-beta.5-pre.6` if you wanna try it out before release
