### ISSUE TITLE
Suggestion: Rich Text Editor to Html module for strings

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#50]
Hi there!

Just wanted to suggest that it will be nice to have a string editor that allows us to format the string and it gets uploaded as a html string in firebase. I know there is the markdown feature but in some scenarios especially for web, it will be cool to save html strings! :)

We could use one of the popular libraries like Quill or CKEditor.

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi 
So for now we are working on building fields for the most common use cases. It is possible that we include an html field sometime (possibly as a plugin dependency if FireCMS keeps getting bigger), but it is not planned in the near future!
I encourage you to try and implement a custom field wrapping your preferred editor. Maybe let me know how it goes afterwards :)

**Comment by faizanabidnaqvi** [comment]
Hi @fgatti675 

I implemented a custom field for rich text editing. I used CKEditor for React library which is super cool. I have a slight issue, however. 

Here is how I wrote it. Quite simple:
```
export const RichTextEditorField = ({property, value, setValue, customProps, touched, error, isSubmitting, context, ...props}: FieldProps<string, RichTextEditorFieldProps>) => {

    return (
        <div>
        <Typography color="textSecondary">{property.title}{property.validation?.required ? "*" : ""}</Typography>
        <CKEditor
            config={ {
                toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote' ],
            } }
            editor={ ClassicEditor }
            data={value ?? ""}
            onChange = {(event: any, editor: any) => {
                const data = editor.getData()
                setValue(data)
                //console.log(data)
            }}
            />
        <FieldDescription property={property}/>
        </div>
    );
}
```

CKEditor has this link button that allows us to add a link to any selected text in the editor. When pressed, this button shows a modal with a text box that allows us to type in the link. The issue is that since the link popup is a modal, it doesn't show up in the side panel which is also a modal.

I was able to show the link box by changing its z-index; which allows showing it but not edit it. Searching online I found it's because of some issue with 'focus' and 'tabindex'. To fix this, I need to access the 'disableEnforceFocus' prop on the side dialog modal. I was wondering if there is a way to access it through the library. And if not, do you have any suggestions on how to fix this.

Here is a screenshot on how it looks after I increased the z-index on the link box (you can notice that the text cursor doesn't appear):
<img width="587" alt="Screenshot 2021-02-22 at 3 35 26 PM" src="https://user-images.githubusercontent.com/5749036/108696662-ab1c5d00-7523-11eb-8319-b97365b489fd.png">

I'll thankful for any suggestions you have! :)

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi 
I have enabled `disableEnforceFocus` in version 0.26.2 
For now it seems fine but we need to keep an eye on the implications.
Let me know if it helps! If it doesn't I'd rather revert the change

**Comment by faizanabidnaqvi** [comment]
Hey @fgatti675 

I just upgraded it to the latest version and it works now. :D Thanks so so much! I'll test around and let you know if any issues do come up.

**Comment by fgatti675** [comment]
I'm closing this issue since adding HTML editing capabilities is currently out of the scope of the CMS and we have made the fixes necessary to allow developers to implement their own custom field if needed!

**Comment by matheuscabralkk** [comment]
@faizanabidnaqvi can you explain how to implement this custom field? I'm trying to import ckeditor into a react component but, no lucky
![teste](https://user-images.githubusercontent.com/24775165/139714240-13616cc4-a572-416f-9c34-3c2c826c08a2.png)

**Comment by faizanabidnaqvi** [comment]
@matheuscabralkk I think that is because typescript can't find any type declarations for it. I fixed this by adding a types/ckeditor/index.d.ts with the following:
```
declare module '@ckeditor/ckeditor5-react';
declare module '@ckeditor/ckeditor5-build-classic';
```

And then including this types folder under typeRoots in tsconfig.json. My tsconfig.json looks like this:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "typeRoots": [
      "types",
      "node_modules/@types"
    ]
  },
  "include": [
    "src"
  ]
}
```

**Comment by matheuscabralkk** [comment]
@faizanabidnaqvi  thank you!

**Comment by fgatti675** [comment]
Hi @ArpadGBondor 
Editing HTML is a fairly complex issue and would take quite some work to get it right for all users.
We recommend integrating a custom component that you can build specifically to suit your needs.
You can add custom components in both self-hosted and Cloud version.
We are happy to continue the discussion in our Discord server :)
https://discord.com/invite/fxy7xsQm3m
Best,
Francesco
