### ISSUE TITLE
Could not find a declaration file for module 'firecms'. 

### ISSUE THREAD

**Issue by vugn** [Camberi/firecms#500]
why do my firecms look like this?

```
Could not find a declaration file for module 'firecms'. 'c:/mypath/node_modules/firecms/dist/index.es.js' implicitly has an 'any' type.
  There are types at 'c:/mypath/node_modules/firecms/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'firecms' library may need to update its package.json or typings.ts(7016)
```

I just Install it and I couldn't find the solutions, I've been searching for a long time

![image](https://user-images.githubusercontent.com/86599375/236409241-5a5b5397-ebd0-4d6f-b40f-56f68f11cd86.png)

**Comment by vugn** [comment]
![image](https://user-images.githubusercontent.com/86599375/236609465-1af1a72a-e81c-446a-89d2-3b5a36627d96.png)
I Just need to add this, please update :)

**Comment by fgatti675** [comment]
Hi @vugn 
It is weird no one has had this issue before!
I have no problem adding this but I am curious as to why you are receiving this message.
Did you just follow the quickstart?

**Comment by fgatti675** [comment]
Hi @vugn 
You were right, something must have changed in the typescript template creation.
I have added your change and deployed version `2.0.0-beta.6-pre.1`
Thank you!
