### ISSUE TITLE
Unable to delete an item from a reference field

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#52]
Hi there!

I am not sure when this started happening; I am unable to remove a reference field (by pressing the x button). It gets stuck in a loading state when pressing the x button. Here is a video:

https://user-images.githubusercontent.com/5749036/107405867-70242d80-6b10-11eb-981d-0b860391b57c.mov

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi ! This should be fixed in version 0.26.0 :)

**Comment by faizanabidnaqvi** [comment]
Yes it is! Awesome work!
