### ISSUE TITLE
Array of map property doesn't work

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#53]
Hi there!

I have an array of map property and each item in the map is of shape {title: string, body: string}. This was working in 0.24 versions but now when you press 'Add' on that property it crashes the app.

Here is how the property is written:
`data: {
          title: "Content",
          validation: { required: true },
          dataType: "array",
          of: {
            dataType: "map",
            properties: {
              title: {
                dataType: "string",
                title: "Title"
              },
              body: {
                dataType: "string",
                title: "Body",
                config: {
                  multiline: true
                }
              }
            }
          }
        },`

Here is the screenshot of what I get:
<img width="1123" alt="Screenshot 2021-02-18 at 8 38 31 AM" src="https://user-images.githubusercontent.com/5749036/108301893-b76f8580-71c4-11eb-839c-6d0a2abaec11.png">

Let me know if this is due to a mistake I am making or just a bug! Thanks a lot! :)

**Comment by fgatti675** [comment]
Not sure what version you were using, but in 0.25.2 there was an update regarding this.
Can you tell me if it is fixed for you in version 0.26.0 ?
Thanks!

**Comment by faizanabidnaqvi** [comment]
Yes it works now! :D
