### ISSUE TITLE
Unable to show additional columns through the properties set in entity collection view

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#54]
Hi there!

Before v0.25.1, I was able to show additional columns where I wanted through the properties set in the entity collection. So, for example, if I had an additional column with id "imagePreview", I could use it in the properties this way:
`
...
properties: ["updatedOn", "imagePreview", "title"]
...
`

But in the latest version, if we use this way there is a type error saying the schema is missing the imagePreview property. Since the imagePreview is an additional column and not a property, I am not sure how to add it to the properties for the schema. 

I'll be thankful if you could look into it. :)

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi ! This should be fixed in version 0.26.0 :)

**Comment by faizanabidnaqvi** [comment]
Works!
