### ISSUE TITLE
Setting empty strings as default values

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#55]
Hi there!

I have a collection where I want each field to be populated even if they are empty. So string fields should be set in firebase but empty that is, field: "". When I try to do this through the defaultValues property in the schema by settings the field as an empty string, it doesn't actually save that field. I assume that is because empty strings are just not added as the property.

Before 0.25.2, I had a workaround. I was populating those fields through the onPreSave function, in this manner:
`
if(!values.title)
values.title = "
`
After updating to the latest version, doing the above causes the app to crash. The error I get is "Too many re-renders". Here is a screenshot:
<img width="1084" alt="Screenshot 2021-02-18 at 11 05 55 AM" src="https://user-images.githubusercontent.com/5749036/108312992-58683b80-71d9-11eb-9cd6-8d250be5d6f3.png">

I'll be thankful if you could take a look!

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi ! This should be fixed in version 0.26.0 :)

**Comment by faizanabidnaqvi** [comment]
It works! :D
