### ISSUE TITLE
Suggestion: Allow opening modal to select reference items programmatically

### ISSUE THREAD

**Issue by faizanabidnaqvi** [Camberi/firecms#56]
Hi there!

I like the new feature that allows us to open the side dialog modal through a hook; that way we can create custom fields that can allow us to use the library's way of creating new documents.

I have another use case, that I was wondering how I could accomplish. Currently, if I have an array of references field in firecms, it shows this nice button 'Edit {field}'. Clicking on that opens the collection dialog where we can search and select any reference items. I wish to have a custom field that allows us to select reference items similar to how firecms already does; but in addition to that, I wish to provide a button that says 'Add new'. The 'Add new' button will allow adding a new document to that reference field and once added, automatically assign the new reference in the document I was editing.

For instance, I have this common' images' collection where I store all images details. Every other document that uses images then has a reference to the images used from the images collection. However, to add a new image, users need to first go to the images collection, upload a new image and then come back to doc they were trying to assign the image to and then select it. It will be much easier if I provided a custom field where they could select existing images through firecms's dialog box but also upload new ones directly to the images collection without navigating away.

I was thinking that this could be accomplished by using the side entity controller to create the new item and allow selecting reference items through a hook that allows me to call the reference selection dialog.

Alternatively, there could probably be another way to do this and I'll be thankful if you have any suggestions.

**Comment by fgatti675** [comment]
Hi @faizanabidnaqvi 
I totally get the use case; I will give it a little though and see the best way to add new entries to array of references inline :)

**Comment by thisoldbear** [comment]
This would be 🌟 amazing 🌟 for a project I'm planning on using FireCMS for and a cherry on top of such a good looking CMS 🤤

**Comment by fgatti675** [comment]
Hi guys, 
This will be the next feature that we will be implementing, allowing adding and selecting new entities within the reference selection dialog :)
We will also address some performance issues affecting that dialog

**Comment by thisoldbear** [comment]
@fgatti675 Amazing news 🕊️

**Comment by fgatti675** [comment]
Hi, with quite some delay, this feature has been shipped in the last alpha version of v2.0!
