### ISSUE TITLE
Reference a subcollection in a Schema

### ISSUE THREAD

**Issue by alpinstang** [Camberi/firecms#57]
I have followed the example referencing other documents like the related products field does. My question is, is it possible to reference a subcollection in the current document? Example code below:

```js
    questions_list: {
      title: "Questions associated with this test",
      description:
        "To add questions, it's recommended to use the CSV uploader.",
      dataType: "array",
      readOnly: true,
      of: {
        dataType: "reference",
        collectionPath: "tests/<currentDocId>/questions", // Is something like this possible?
      },
    },
```
Note the comment for where I am referring to in the question. Thank you!

**Comment by fgatti675** [comment]
Hi @alpinstang :)
I think this should be achievable with a PropertyBuilder. You can replace your property declaration with a function:
```
    questions_list: ({entityId}) => ({
      title: "Questions associated with this test",
      description:
        "To add questions, it's recommended to use the CSV uploader.",
      dataType: "array",
      readOnly: true,
      of: {
        dataType: "reference",
        collectionPath: `tests/${entityId}/questions`, 
      },
    }),
    ```
    Let me know if it works out for you!

**Comment by alpinstang** [comment]
@fgatti675 Thank you for your reply! I will try this out. Great project 👍👍

**Comment by fgatti675** [comment]
Thank you!
