### ISSUE TITLE
Date format for the DateTimePicker component

### ISSUE THREAD

**Issue by fabarea** [Camberi/firecms#58]
Hi, 

Is there a way to format the date ?

We are missing a configuration, I guess in the DateTimeField component?

https://github.com/Camberi/firecms/blob/master/src/form/fields/DateTimeField.tsx

According to the documentation we should wrap the component in some kind of Provider.

https://material-ui-pickers.dev/localization/date-fns

**Comment by fabarea** [comment]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/620730/109958673-bec78080-7ce6-11eb-998d-07545788387a.png">

**Comment by fgatti675** [comment]
Added in version 0.29.0 ;)
You can change the locale (though it is only modifying the language of the date for now)
And you can also override the full format
