### ISSUE TITLE
Enable other authentication methods from FireCMS

### ISSUE THREAD

**Issue by eliataylor** [Camberi/firecms#60]
Let's enable all OAuth providers. Let's start with Email and Phone.

https://firebase.google.com/docs/auth/web/firebaseui

(I'll setup the necessary App keys for FB, Github, Twitter, etc...)

**Comment by fgatti675** [comment]
Hi @eliataylor 
Currently FireCMS supports all the methods implemented by FirebaseUI, which is user underneath.
You can pass enable the methods you want with the prop `signInOptions` in `CMSApp`

**Comment by eliataylor** [comment]
hahhha. my apologies @fgatti675 , I wondered where this Issue went. I was in the wrong repository!

https://github.com/eliataylor/clock-agendas/issues/16

I LOVE your project by the way. We're building open open source platform around it.

 Is there a good first issue I can help with?

**Comment by fgatti675** [comment]
Haha no worries @eliataylor !
Thanks a lot for your nice words 🙌 
The best way you can help me right now is implementing your project and giving us feedback on your experience, pain points / things to improve :)

**Comment by TheAussieStew** [comment]
Hi @fgatti675,

Thanks for making and maintaining this awesome looking library first of all.

I'm getting this error if I use the email provider:

The identity provider configuration is not found. 

What do you reckon?

**Comment by fgatti675** [comment]
Hi @TheAussieStew did you enable the email provider in your Firebase  admin panel?

**Comment by TheAussieStew** [comment]
Yes, I did, currently Google, Email and Anonymous are enabled. For now I've resorted to using the Google auth provider that comes by default, not using the SignInOptions
