### ISSUE TITLE
Broken links in the Custom Fields documentation

### ISSUE THREAD

**Issue by LaurentEscalier** [Camberi/firecms#66]
Hi there 👋 

Opening an issue to notify about the two broken links in the [Custom Fields section](https://github.com/Camberi/firecms#custom-fields) of the docs.

<img width="843" alt="Screen Shot 2021-03-31 at 10 53 23" src="https://user-images.githubusercontent.com/62994416/113118296-9bbdbd00-920f-11eb-9ebe-255629112e73.png">

**Comment by fgatti675** [comment]
Thanks for the catch! Fixed :)

**Comment by LaurentEscalier** [comment]
Thank you for the quick fix 🙏
