### ISSUE TITLE
[Feature request] Add support for reference field properties in the list views

### ISSUE THREAD

**Issue by LaurentEscalier** [Camberi/firecms#68]
Hi there 👋

_I must first apologize in case this is already supported, but it wasn't in the version I experimented with last week._

The CMS features a `properties` option in the [Collection Configuration](https://github.com/Camberi/firecms#collection-configuration) that allows to white list columns that should show up in the List view.

This option does not seem to support properties of [reference fields](https://github.com/Camberi/firecms#reference) and I think that would be a nice addition to this project.

```typescript
// Schema with reference fields

const articleSchema = buildSchema({
    ...
    properties: {
        ...
        category: {
            title: "Category",
            dataType: "reference",
            collectionPath: "categories",
            validation: { required: true },
        },
        author: {
            title: "Author",
            dataType: "reference",
            collectionPath: "authors",
            validation: { required: true },
        }
        ...
    }
    ...
```

```typescript
// Add support for reference field properties category.title and author.name

const navigation: EntityCollectionView<any>[] = [
    ...
    {
        relativePath: "articles",
        schema: articleSchema,
        name: "Articles",
        properties: ["title", "summary", "category.title", "author.name"]
    }
    ...
];
```

Thank you for reading 🙏  and sorry that I am not able to contribute for the moment.

**Comment by fgatti675** [comment]
Unfortunately this is not implemented at the moment, though we can consider it for the future!
For now you can use Additional columns to generate read only columns that are mapped to any value you want

**Comment by LaurentEscalier** [comment]
@fgatti675 Thanks for answering on that. I'll be looking into the [additional columns](https://github.com/Camberi/firecms#additional-columns) option. Can you maybe point to an example schema using this feature ? Thanks !

**Comment by fgatti675** [comment]
Sure, there is an example column in:
https://github.com/Camberi/firecms/blob/master/example/src/SampleApp/schemas/products_schema.tsx#L250
(in your case you don't need to use the `AsyncPreviewComponent` since you can simply return the value of the map you need)
Then that delegate is used here:
https://github.com/Camberi/firecms/blob/12fd62496b24d8951527fab7e285ca35d8b2e7af/example/src/SampleApp/SampleApp.tsx#L54
