### ISSUE TITLE
Can image be in URL format instead?

### ISSUE THREAD

**Issue by shaniceweiwei** [Camberi/firecms#7]
Can image be uploaded to firebase storage still but storing the URL instead of just the path name in String?

**Comment by faizaand** [comment]
I've made this change in a fork, the commit is linked: https://github.com/faizaand/firecms/commit/9b074f889061fe499b2a4d832a2f53594421779c

You can adopt my same code; I made changes to `example/src/index.tsx` in here so you'll want to ignore that file. The files that are relevant to this change are `src/form/fields/StorageUploadField.tsx` and `src/preview/PreviewComponent.tsx`.

**Comment by shaniceweiwei** [comment]
> I've made this change in a fork, the commit is linked: [faizaand@9b074f8](https://github.com/faizaand/firecms/commit/9b074f889061fe499b2a4d832a2f53594421779c)
> 
> You can adopt my same code; I made changes to `example/src/index.tsx` in here so you'll want to ignore that file. The files that are relevant to this change are `src/form/fields/StorageUploadField.tsx` and `src/preview/PreviewComponent.tsx`.

I'm sorry if this is a stupid question, I'm super new to react and npm thingy, how do I replace dependency with your forked project? I've tried `"yarn save faizaand/firecms"` or `"yarn upgrade faizaand/firecms"` but when I `"yarn start"` it says 
```
./src/index.tsx
Module not found: Can't resolve '@camberi/firecms' in '/Users/developer/projects/ReactApp/cms/src'
```
what am I doing wrong?

**Comment by faizaand** [comment]
@shaniceweiwei No such thing as a stupid question! That's probably because my repository is not bundled for distribution - it is not intended to be used as an actual package so I didn't bother bundling it. You can try cloning it locally, running `npm install` inside, and then referencing it via a file dependency in your CMS project's `package.json`. That would go something like "file:path/to/faizaand-firecms/".

**Comment by fgatti675** [comment]
Hi! I am currently looking into this :)
@faizaand feel free to submit PRs whenever you have any change you'd like to see merged

**Comment by fgatti675** [comment]
Hi @shaniceweiwei and @faizaand , I have added this feature in version 0.13.0
Now in the storage config, you can set the flag `storeUrl` to true, which will save the download URL instead of the reference.

**Comment by shaniceweiwei** [comment]
> Hi @shaniceweiwei and @faizaand , I have added this feature in version 0.13.0
> Now in the storage config, you can set the flag `storeUrl` to true, which will save the download URL instead of the reference.

```
config: {
        storeUrl: true,
        storageMeta: {
          mediaType: "image",
          storagePath: "banners",
          acceptedFiles: ["image/*"]
        }
      },
```
Is this the correct syntax? Because it does not seems to work, it is still keeping `files/finename.jpg` instead of the whole http url.
