### ISSUE TITLE
Parent Document or Collection  Reference ID Access onPreSave

### ISSUE THREAD

**Issue by justbcuz** [Camberi/firecms#70]
Is there any way to access the parent document or collection  reference ID prior to saving a new entity.

The use case is, I am building collection with sub-collections, I would like to the parent document ID to be a property of the child. I know I can achieve this with a post save/update firebase function, but the parent document reference should already be available to me via the framework. Understandably, the onDelete callback pass in EntityDeleteProps which contains and Entity property with a document reference. 

Can the onPreSave be updated to contain a "parentEntity" property with a DocumentReference or  "parentCollection" property with a CollectionReference? This way I can traverse the Firestore references to get my needed IDs before the save is completed.

**Comment by fgatti675** [comment]
Hi @justbcuz :)
In the preSave hook there is a `collectionPath` property that contains the full path of the collection of the entity, including the parent entity id. Could you use that for now?
I am going to check if I can add all the parent entities (not just the last one) to the hook :)

**Comment by justbcuz** [comment]
@fgatti675 Thank you, that sounds awesome! Let me know when you get a chance to look at this.

In the meantime I will definitely look at the `collectionPath` property. I appreciate the quick response.

**Comment by fgatti675** [comment]
For anyone interested or having a similar issue.
There is a hook called [useNavigationFrom](https://firecms.co/docs/api/functions/usenavigationfrom/) that will return the resolved navigation entries that the CMS uses internally.
That hook can only be used in a custom component.
If you are in a callback context like preSave, you can use the function `getNavigationFrom` that works the same (but you need to pass your [CMSAppContext](https://firecms.co/docs/api/interfaces/cmsappcontext)
