### ISSUE TITLE
[Feature] Map data type similar to an Array with  the "of" attribute

### ISSUE THREAD

**Issue by justbcuz** [Camberi/firecms#71]
Is it possible to create a Map data type similar to an Array with the "of" attribute, so we can have a dictionary of defined key value pairs, but the key and values are defined and added in the CMS UI.

Thanks,
Justin

**Comment by fgatti675** [comment]
Hi @justbcuz 
So the CMS supports regular `map` data types where the developer defines the keys and possible values.
It is currently not possible to allow users to define the keys.
What you can do is build your own `CustomField`.
You can take the example in 
https://github.com/Camberi/firecms/tree/master/example/src/SampleApp/custom_shaped_array
as a reference.
In that example we create a custom field as a react component that generates a field of data type `array` where each field in the index is assigned to a specific property, such as `[123, "abc"]`
