### ISSUE TITLE
make `useSideEntityController()` available outside of `CMSApp`

### ISSUE THREAD

**Issue by eliataylor** [Camberi/firecms#72]
Thanks again for all your work with this!

We were hoping to open any entity form from buttons around our app  (outside of the the `CMSApp` component).

The doc's example seems to suggest that's the hook's intent, but [our implementation]( https://github.com/DemocraseeClub/website/issues/32) so far does nothing.

**Comment by fgatti675** [comment]
Hi @eliataylor 
So the hook uses a Context that is provided by the `CMSApp` component, which is also the one that contains the view that is being displayed and is also coupled with the main navigation of the app. So the component calling `useSideEntityController` need to be under `CMSApp` in order to work.
I think I need to understand better your use case to propose a solution. 
In the long run we would like to break FireCMS into a set of components that can be used as a whole or independently. 
It would help me to know how you are integrating FireCMS into your app. I'm specially curious to see how you come around authentication! Is there anywhere I can check it?

**Comment by eliataylor** [comment]
@fgatti675 thanks.  We're currently rebuilding our Auth system per https://github.com/DemocraseeClub/website/issues/35. All the code is open source.

In short, we'll being using Functions to connect `firebase.auth` to `firestore.collection.users`. Eventually we may need something like `firestore.collection.permissions` to hold a more granular list, but that seems extremely complicated to implement with firestore's Security Rules. So we're securing the `firestore.collection.users.roles` field with:

```
match /users/{userId} {
      allow read: if true;
      allow create: if !request.resource.data.keys().hasAny(['roles', 'citizencoin'])
      allow update: if (request.auth.uid == request.resource.id && (!request.resource.data.keys().hasAny(['roles', 'citizencoin']))) || hasRole('admin');
      allow delete: if request.auth.uid == request.resource.id || hasRole('admin');
    }
 ```

**Comment by fgatti675** [comment]
Hi @eliataylor 
I meant more how you are using FireCMS in conjunction with a bigger React app. FireCMS is meant to be used a full app and it is not really ready to be used as a component for now.
But I have tried running your project locally and I'm surprised to see it is mostly working!
The issue you face would probably be solved if we split `CMSApp` into something like `CMSAppProvider` (that you can place at the root of your app) and then `CMSMainView` that contains only the views of the CMS. That would also allow you to use internal components such as entity collections and hooks at any level of your app.
Unfortunately that would take some time and I can't really give you a clear timeline for it :(

**Comment by fgatti675** [comment]
Hi @eliataylor 
I have split the code of `CMSApp` in version 0.36.1 into 2 main components: `CMSAppProvider` (which contains all the providers and contexts used by the CMS, including the side dialogs) and `CMSMainView` (which includes the views of the CMS)
`CMSApp` is still there and now is in charge of just initialising Firebase and these 2 components.
I have created an example that uses this approach instead of the full app and also is in charge of initialising Firebase:
https://github.com/Camberi/firecms/blob/master/example/src/SimpleAppWithProvider.tsx
I haven't done extensive testing integrating with other components, so let me know how it goes!
Best,

**Comment by eliataylor** [comment]
@fgatti675 that worked well! Gracias!!! 

I can imagine why, but one unfortunate requirement is that `CMSMainView` still has to be mounted with `display:none` where ever we call `useSideEntityController`. See our implementation here: https://github.com/DemocraseeClub/website/blob/8a3655b62105082a1527a0b0159ea309c2e0574a/src/App.js#L119

Otherwise, a dream would be to have a little more control over the form layout but this will definitely work for now.

Meanwhile, join this program - https://github.com/sponsors/community - or let me know how we can support a little.

**Comment by fgatti675** [comment]
Hi @eliataylor 
You are right, the side dialog view was in the CMSMainView, which was wrong. 
I have moved it to the provider in version 0.38.2 so you can use it without the main view.
The only breaking change is you need to move the theme data (colors and font) from the main view to the provider
About the form, could you open another ticket explaining what kind of customization you would like?
Also, I'll check the sponsors program :)
Thank you!

**Comment by fgatti675** [comment]
Hi @eliataylor 
Just to let you know we have enabled the sponsors program!! Really excited about it :)
https://github.com/sponsors/Camberi
Hope your project is going good!
Let me know if I can support you in any way

**Comment by eliataylor** [comment]
> It would help me to know how you are integrating FireCMS into your app. I'm specially curious to see how you come around authentication!

@fgatti675 , regarding authentication, I wrote a function to merge the Provider data with our Firebase user collection: 

https://github.com/DemocraseeClub/website/blob/master/functions/src/index.ts#L219

Inside of your `CMSAppProvider.authentication` I'm trying to `authController.setAuthResult(mergedUser)`:

https://github.com/DemocraseeClub/website/blob/master/src/views/firebaseCMS/FirebaseCMS.tsx#L184

This does not seem to work, so I'm wondering how / if I should overwrite the FireCMS auth context with the current user's complete profile?

**Comment by eliataylor** [comment]
this screenshot shows `setAuthResult` [FirebaseCMS.tsx](https://github.com/DemocraseeClub/website/blob/master/src/views/firebaseCMS/FirebaseCMS.tsx#L184) and the `setAuthResult` in [footer.js](https://github.com/DemocraseeClub/website/blob/master/functions/src/index.ts#L219)

![Screen Shot 2021-05-24 at 7 13 31 PM](https://user-images.githubusercontent.com/6335974/119429725-47d9cc80-bcc4-11eb-8cd7-f4fd196c60ba.png)

**Comment by eliataylor** [comment]
@fgatti675 , i dug into the FireCMS source and now realize the user does need to be an instance of the [firebase.User](https://firebase.google.com/docs/reference/js/firebase.User). 

Basically, i'm trying to access our firestore `role` field on the user available in your `PermissionsBuilder` as well the `useAuthController`. Is either possible?

**Comment by eliataylor** [comment]
As a potential solution, could we expand the [NavigationBuilderProp](https://github.com/Camberi/firecms/blob/672b6498948541cb7a02e6d136f3bff2a8a8dcb2/src/CMSAppProps.tsx#L123) support another property like `firestore: <firebase.firestore.DocumentData>` ?

**Comment by fgatti675** [comment]
Hi @eliataylor 
If I understand it correctly, you are copying the Firebase user to your custom Firestore collection. 
The permission builder is going to give you the firebase.User but you need the Firestore document where the roles are stored.
What you need to do is to use the user ID to fetch the specific document from your `users` collection.
```
await firestore.collection("/users")
    .document(USER_ID)
    .get()
    .then((snapshot) =>
        // return your roles here!
));
```
`PermissionsBuilder` can be async so you can use the await function or use a promise.


Just to clarify, there are also native roles you can assign to Firebase users, but you can only access them from a backend environment, using the admin code from Firebase. 

BTW, thanks a lot for your sponsorship!

**Comment by eliataylor** [comment]
@fgatti675 , i understand how to query for the roles. Now i'm trying to add it to the FireCMS context so I don't have to do that all over the place.

*How do I pass the result of that query to your `permissions` and `useAuthController` functions?

**Comment by eliataylor** [comment]
> Just to clarify, there are also native roles you can assign to Firebase users, but you can only access them from a backend environment, using the admin code from Firebase.

Where are these? I only see solutions using Firestore fields like https://firebase.google.com/docs/firestore/solutions/role-based-access

**Comment by eliataylor** [comment]
> BTW, thanks a lot for your sponsorship!

We'll try to keep that recurring.

**Comment by eliataylor** [comment]
@fgatti675 , i now realize I can just `const [fbUser, setFbUser] = useState<Object>();` and pass the `fbUser` to through my schema builders! GREAT!

Now what about `useAuthController()` or should I just create and manage my own context / redux store?

**Comment by fgatti675** [comment]
Ah sorry! I misunderstood.
How about if we add an `extras` and `setExtras` state methods of type any in authController so you can store your user document there?

**Comment by fgatti675** [comment]
Ok, so I have removed the `authResult` fields as they were legacy from internal use and were not being used, and only causing confussion.
I have also added `extra` and `setExtra` properties in `useAuthController()` in version 0.39.1
That way you can store your `fbUser` there and access it from wherever you need in your app :)
I called it extra so it's generic enough for anyone to use.

> Where are these? I only see solutions using Firestore fields like https://firebase.google.com/docs/firestore/solutions/role-based-access
What I meant is actually called "custom claims" and custom tokens, but I don't think is the right way to go in your case:
https://firebase.google.com/docs/auth/admin/create-custom-tokens
