### ISSUE TITLE
Allow passing firebase.initializeApp object rather than firebaseConfig

### ISSUE THREAD

**Issue by eliataylor** [Camberi/firecms#73]
(another enhancement request)... To avoid issues surrounding

> "Warning: Firebase is already defined in the global scope. Please make sure Firebase library is only loaded once."

It would be nice to support passing `CMSApp` the `firebase.initializeApp(config)` object and thus skip instantiating later. 

some other details on [our issue](https://github.com/DemocraseeClub/website/issues/21)

**Comment by fgatti675** [comment]
Interesting, the `CMSApp` component has this check:
```
        if (firebase.apps.length > 0)
            return;
```
So in theory it should not try to initialise firebase again if it was already previously.
You are initialising Firebase from within a <script/> tag?

**Comment by eliataylor** [comment]
yes: https://github.com/DemocraseeClub/website/blob/master/public/index.html#L38

**Comment by fgatti675** [comment]
Check https://github.com/Camberi/firecms/issues/72#issuecomment-829411425 since it should solve this issue as well :)
You still need to pass the config to the CMS components with that approach but they will not try to initialise Firebase.
