### ISSUE TITLE
NextJS Issue.

### ISSUE THREAD

**Issue by choguun** [Camberi/firecms#74]
Hi

I got a problem when using it in NextJS project.
I showed a message below.

./node_modules/typeface-space-mono/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\@camberi\firecms\dist\index.modern.js

How to fix this.

Thanks

**Comment by fgatti675** [comment]
Hi @choguun 
Can you try with version 0.37.0?
I have removed that import

**Comment by choguun** [comment]
same problem in version 0.37.0

**Comment by choguun** [comment]
same problem in version 0.39.0
Do you have any updates?

**Comment by fgatti675** [comment]
Hi @choguun 
Unfortunately FireCMS depends on FirebaseUI which does not support SSR and there is no easy solution unless we replace that library all together, it would mean reimplementing all the login flow on our own.
It is not likely to happen.
There are people already asking for SSR support for FirebaseUI so maybe you can try there!

**Comment by fgatti675** [comment]
For anyone landing here, FireCMS can now be used with next.js, just by disabling SSR.
```
const Admin = dynamic(() => import("../your_firecms_app"), { ssr: false });
```
