### ISSUE TITLE
Unique field validation fails on nested object

### ISSUE THREAD

**Issue by mauriceackel** [Camberi/firecms#75]
Hi there, I have the following schema:

```javascript
export const problematicSchema = buildSchema({
  name: 'Foobar',
  properties: {
    actions: {
      title: 'Actions',
      description: 'Possible user actions',
      validation: { required: true },
      dataType: 'array',
      of: {
        dataType: 'map',
        properties: {
          name: {
            title: 'Name',
            description: 'Text that will be shown on the button',
            validation: { required: true, unique: true },
            dataType: 'string',
          },
          type: {
            title: 'Type',
            description: 'Action type that determines the user flow',
            validation: { required: true, unique: true },
            dataType: 'string',
            config: {
              enumValues: {
                foo: 'Bar',
              },
            },
          },
        },
      },
    },
  },
});
```

The important thing is, that there is a `unique` validator set in the nested `name` and `type` fields respectively. Now, as soon as I set a value in the UI, an error is thrown:

```
Unhandled Rejection (FirebaseError): Function Query.where() called with invalid data. Invalid field path (undefined[name]). Paths must not contain '~', '*', '/', '[', or ']'
```

My guess is, that [this](https://github.com/Camberi/firecms/blob/842fa8a9c90c5fdd1388e78f7b2c78ff71e8359c/src/form/validation.ts#L76) line is executed. Hence the `undefined[name]` value that is subsequently passed to [this](https://github.com/Camberi/firecms/blob/30935d2652c3169d35f9ebb921d8597cd353e506/src/models/firestore.ts#L541) function and fails at [this](https://github.com/Camberi/firecms/blob/30935d2652c3169d35f9ebb921d8597cd353e506/src/models/firestore.ts#L556) line.

**Comment by fgatti675** [comment]
Thanks for the catch @mauriceackel !
I'll look into it :)

**Comment by fgatti675** [comment]
Checking this, Firestore does not allow the kind of queries over indexes in arrays.
Also, it is not totally clear to me what your intent is with this configuration.
Would like...
a) ...to have unique values in each entry of the array **within** the same document?
b) ...to have unique values across all the arrays in **all** documents?
In any case we will fix the code so it does not break and just shows a warning

**Comment by mauriceackel** [comment]
Hi @fgatti675 and thanks for looking into this!

My use case would be what you have described in `a)`. Image you have have an array of elements where each one has a `name` property. The name is southing you would show to the user (i.e. as the text of a button). So you want all names to be distinct so that they are distinguishable for a user.

I think this should be able to check for using yup and a custom validator as we would already have all the values in the document and don't need to query any additional documents.

**Comment by fgatti675** [comment]
Got it!
In this case I would need to think if we want to keep the API as it is or create a different prop, something like `uniqueInArray` which has no effect outside arrays.
It's a bit tricky considering the different data structures you can have... suggestions are welcome!

**Comment by mauriceackel** [comment]
I think in the end it depends on how easy it is to check whether the current entity being validated is part of an array. If this can be achieved rather easily (perhaps by passing some parameters [here](https://github.com/Camberi/firecms/blob/842fa8a9c90c5fdd1388e78f7b2c78ff71e8359c/src/form/validation.ts#L196) ??), I would vote for keeping the name `unique` and handling it correctly in the validation logic.

However, if it is really tricky to figure out the context of the entity when evaluating, an additional property might make sense (though this would also need to check if it is outside an array I guess)

**Comment by fgatti675** [comment]
Hi @mauriceackel 
I have ended up adding the flag `uniqueInArray` that is meant to fulfil your use case. It works with direct children of array properties or direct children of a MapProperty if specified as `of`.
I felt that reusing the `unique` (which now means the only value in the collection), would be confusing if it had a different behaviour under an array.
Let me know if it works for you!

**Comment by mauriceackel** [comment]
Hi @fgatti675, thanks for the quick proposal 💯 I added the the property like so:

```javascript
actions: {
  title: 'Actions',
  description: 'Possible user actions',
  validation: { required: true },
  dataType: 'array',
  of: {
    dataType: 'map',
    properties: {
      name: {
        title: 'Name',
        description: 'Text that will be shown on the button',
        validation: { required: true },
        dataType: 'string',
      },
      type: {
        title: 'Type',
        description: 'Action type that determines the user flow',
        validation: { required: true, uniqueInArray: true },
        dataType: 'string',
        config: {
          enumValues: {
            complete: 'Complete',
            continue: 'Continue',
          },
        },
      },
    },
  },
},
```

But when I add an element to my array, react throws an error:

<img width="1027" alt="Bildschirmfoto 2021-05-03 um 17 49 03" src="https://user-images.githubusercontent.com/20804369/116899459-db752b80-ac37-11eb-8109-517817fe0442.png">

**Comment by mauriceackel** [comment]
How ever I can confirm that the original error is not longer thrown when I try to set the `unique` property 👍

**Comment by fgatti675** [comment]
Can you try version 0.38.1?

**Comment by mauriceackel** [comment]
Works as expected 🚀 Your on 🔥😃

**Comment by fgatti675** [comment]
Haha glad to hear @mauriceackel 
Have a good day!
