### ISSUE TITLE
feature: Allow path parameters in additional views

### ISSUE THREAD

**Issue by mauriceackel** [Camberi/firecms#76]
Hi there and thanks for the awesome project.

I am currently building a custom view and I would like to pass it some path parameters. I added those to the 'path' property of my CMSView (i.e. path: 'myawesomepath/:param') and I can already retrieve the parameter value by using the `useParams` hook from  react router.

However, whenever I open the view from the Dashboard, I will be navigated to 'myawesomepath/:param' (i.e. it uses the parameter placeholder). Is there a way to specify a path (including parameters) and an additional property (i.e. `navUrl`) that will be used for navigation when the card is clicked on the dashboard?

I would imagine it to be like:

```javascript
views: [
  {
    path: '/myawesomepath/:param',
    navUrl: '/myawesomepath',
    name: 'Foo',
    view: <Foo />,
    group: 'Bar',
  },
],
```

**Comment by fgatti675** [comment]
Hi @mauriceackel I'm thinking about this, and the best way to make it work for your use case while keeping a clean API.
Effectively you need to be able to add the same view to the router with different paths '/myawesomepath/:param' and '/myawesomepath'
My preferred solution would be to add a flag `hideFromNavigation` that when set to true simply does not include the entry in the main menu but yes in the router. That way you can add the view as many times as you need :)
Would that work for you?

**Comment by mauriceackel** [comment]
Hi @fgatti675 , I understand your rationale behind this Idea though I'm not 100% how to think about having to specify a view twice then.. But I think the idea of being able to add routes that are not necessarily visible in the dashboard is a good one!

I'm thinking about whether there might be a strict destination between defining view/routes and defining the dashboard, like you do when defining routes in the react router and then handling the navigation elsewhere.. However, I guess this would require a major refactoring.

This being said, I think the approach you described sound fairly reasonable and would probably not require a large refactoring.

**Comment by fgatti675** [comment]
Hi @mauriceackel 
A couple of changes in version 0.39.0, you can specify multiple paths in views, e.g: `path: ["mypath", "mypath/:param"]` and only the first one is considered to the navigation drawer.
Additionally `hideFromNavigation` has also been added as a prop since it could be useful for someone else.
Let me know if it works for you :)

**Comment by mauriceackel** [comment]
This works great! Thanks a lot @fgatti675 🚀
