### ISSUE TITLE
bug: Server timestamp forced on creation of timestamp fields

### ISSUE THREAD

**Issue by mauriceackel** [Camberi/firecms#77]
When one creates a new document, which has fields of type timestamp, he/she can set a date. However, on save the values will be overwritten and instead the server timestamp will be used.

I believe this is due to this part of the code: https://github.com/Camberi/firecms/blob/30935d2652c3169d35f9ebb921d8597cd353e506/src/models/firestore.ts#L483-L484

where the existing value is overwritten with the server timestamp FieldValue if the entity has status `new`.

Expected behavior: When the date is defined by the user, this date should be stored.

**Comment by fgatti675** [comment]
Thank you @mauriceackel 
Just to clarify, you did not set the `on_update` or `on_create` flags right?

**Comment by mauriceackel** [comment]
Hey, no I have not set any flags. I just set the dataType to `timestamp`.

**Comment by fgatti675** [comment]
Should be fixed in version 0.38.0 :)

**Comment by mauriceackel** [comment]
Amazing 🚀❤️🎉 Thank you!

**Comment by mauriceackel** [comment]
I can confirm that this works in my setup with version 0.38.0

**Comment by fgatti675** [comment]
Great!
