### ISSUE TITLE
[Feature] Statically set schemas

### ISSUE THREAD

**Issue by PupoSDC** [Camberi/firecms#78]
It would be great if we could do something like this:

```ts
import { buildSchema } from '@camberi/firecms';
import { Category } from "@my-projects/schemas";

export const categorySchema = buildSchema<Category>({
 /** everything here stays the same, but now, typescript complains if the schema mismatches with the Category. **/
});
```

Thanks a lot for your work here 💯

**Comment by fgatti675** [comment]
Hi @PupoSDC 
`buildSchema` is just a utility function that just returns the input. It is used to take benefit of Typescript types and get the IDEs perks. 
```
export function buildSchema<Key extends string = string>(
    schema: EntitySchema<Key>
): EntitySchema<Key> {
    return schema;
}
```
This is the code for the function. The first generic type is expecting a `Key` which are strings that represent the developer defined keys of the properties, and should not be instantiated.
I don't know exactly what your `Category` object has, but I assume you can just delete the generic type and it should be fine:
 ```
 import { buildSchema } from '@camberi/firecms';
import { Category } from "@my-projects/schemas";

export const categorySchema = buildSchema({
 /** everything here stays the same, but now, typescript complains if the schema mismatches with the Category. **/
});
```

**Comment by PupoSDC** [comment]
Thank you for your prompt reply. This is more of a feature request, than a call for help.

Let's imagine the following simple case:

```tsx
// This category type is what already exists in my collection.
type Category = {
 name: string;
}

// And now i do:
export const categorySchema = buildSchema({
  name: "category",
  properties: {
    naame: {
      type: "string",
      name: "name",
    }
 }
});
}
```

This would work fine, but the type of my categories would mismatch with what I actually intended to do. My feature Request would be that `buildSchema` takes an optional template parameter with the typescript type im going write down as a schema, so that if i do screw up, static analysis will save me.

The feature request is similar to what Yup offers: https://github.com/jquense/yup/blob/master/docs/typescript.md

**Comment by fgatti675** [comment]
Ah I understand! So getting statically type checks based on your Typescript interfaces.
Makes total sense, and would make a nice enhancement.
I'm adding it to the backlog. If you feel like giving a shot at the implementation let me know!

**Comment by PupoSDC** [comment]
I waI have some free time on friday, I will try to do it then. Time to polish my TS skills <3

**Comment by fgatti675** [comment]
Hi @PupoSDC 
Thanks a lot for your PR!! I have merged it but modified it a little bit. The function you need is now called `buildSchemaFrom`
and I have modified it slightly. I have also tried checking the property data types based on the Typescript types but failed!
I already tried once and failed as well, I have to admit Typescript has defeated me here!
I am pretty sure it's possible but I am getting something wrong.

It is not released yet, but it is merged into the `master` branch so if you would like to use it you can link your project to it directly.

If anyone sees this and is willing to try, the goal is to be able to type check property data types based on a given Typescript type. 

A simplified version of the model would be:

```
interface EntitySchema<Key extends string = string, T extends any = any> {
    properties: Record<Key, Property<T>>;
}

type Property<T = any> =
    T extends string ? StringProperty :
        T extends number ? NumberProperty : never;


interface StringProperty {
    dataType: "string";
}

interface NumberProperty {
    dataType: "number";
}

function buildSchemaFrom<Type extends Partial<{ [P in Key]: T; }>,
    Key extends string = Extract<keyof Type, string>,
    T = any>(
    schema: EntitySchema<Key, T>
): EntitySchema<Key, T> {
    return schema;
}

type Product = {
    name: string,
    price: number,
}

export const productSchema = buildSchemaFrom<Product>({
    properties: {
        name: {
            dataType: "string"
        },
        price: {
            dataType: "string", // THIS SHOULD FAIL
        },
        // missing: { // This fails if uncommented, which is expected
        //     dataType: "string",
        // },
    }
});
```
 If anyone manages to get the simplified version working we can probably escalate it to the whole app :)

**Comment by PupoSDC** [comment]
Thanks a lot! Hurray!

I will see if i can improve on this. But for now im already quite happy with this functionality!

Cheers!
