### ISSUE TITLE
timestamp is not saved

### ISSUE THREAD

**Issue by shaniceweiwei** [Camberi/firecms#8]
DataType "timestamp" has current date & time displaying in form but never saved in firestore unless it was manually selected by user.

**Comment by shaniceweiwei** [comment]
I think for the time being I just do it with `onPreSave`  and check if it is undefined then set `new Date()`.

**Comment by fgatti675** [comment]
Hi @shaniceweiwei, that was a bug, displaying the current date when it was not set.
In version 0.13.0 this is fixed and empty dates don't show up. 
It probably makes sense to add some additional props to add custom behaviours, like initialise as the current date, or update on save. Ideas are welcome! 👍

**Comment by shaniceweiwei** [comment]
> Hi @shaniceweiwei, that was a bug, displaying the current date when it was not set.
> In version 0.13.0 this is fixed and empty dates don't show up.
> It probably makes sense to add some additional props to add custom behaviours, like initialise as the current date, or update on save. Ideas are welcome! 👍

Yes, maybe to have a config that allow us to preset Date() ?
By the way, is 0.13.0 released yet? :D

**Comment by fgatti675** [comment]
It is :)
https://www.npmjs.com/package/@camberi/firecms

I have added your request to a newly created backlog: https://github.com/Camberi/firecms/projects/1?add_cards_query=is%3Aopen

**Comment by fgatti675** [comment]
Regarding this ticket, you can set now the `autoValue` flag to timestamp properties, so timestamps get updated with the server value on creation or update
