### ISSUE TITLE
Tried replicating the example got the following error

### ISSUE THREAD

**Issue by Rohithgilla12** [Camberi/firecms#90]
```
./node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js
Attempted import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper' (imported as 'v').
```

**Comment by fgatti675** [comment]
Hi @Rohithgilla12 
Seems to be related to a bug in the latest version of Firebase (8.6.4)
https://github.com/firebase/firebase-js-sdk/issues/4977
I got the same error with that one but it works fine with 8.5.0
You can use that version in the meantime :)

**Comment by Rohithgilla12** [comment]
Hey, it works thanks for the amazing package and support.
You are amazing.
Closing the issue

**Comment by fgatti675** [comment]
Thank you @Rohithgilla12 !
That's really nice of you :)
